import pandas as pd, numpy as np, json
p = pd.read_parquet("data/panel_daily.parquet")
print("panel rows", len(p), "codes", p.code.nunique(), "dates", p.date.nunique())
print("date range", p.date.min(), p.date.max())
print(p.dtypes.to_dict())
print(p.head(3).to_string())
m = pd.read_parquet("outputs/ml/matrix_h10_t30_s5.parquet")
print("\nmatrix rows", len(m), "cols", len(m.columns))
print("matrix codes", m.code.nunique(), "dates", m.date.nunique())
print("date range", m.date.min(), m.date.max())
print("dup (code,date)", int(m.duplicated(['code','date']).sum()))
print("base rate high", m.label_high.mean(), "resolved", m.resolved.mean())
print("sorted by code,date?", m[['code','date']].equals(m.sort_values(['code','date']).reset_index(drop=True)))
print("\ncols:", list(m.columns))
