"""Audit the published reports and documents for internal consistency.

This repository publishes numbers in three places that can drift apart:

* ``reports/*.json`` — machine-readable ground truth, regenerated by the ``src``
  and ``src.ml`` modules;
* the Markdown documents (``README.md``, ``TARGET_70PCT.md``, ``RESULTS.md``);
* the audit documents under ``audit/``.

Nothing previously checked that a figure quoted in prose still matched the report
it came from. That gap has already produced two real defects in this project: a
precision ceiling quoted as 20.23% after the grid was densified, and a lift
quoted as 3.87x then "corrected" to 3.58x when the exact pooled value is 3.91x.
Both were found by hand, late. This module finds that class of error
mechanically.

Checks performed
----------------
1. Arithmetic inside each report: lift equals precision divided by base rate,
   signal and hit counts are consistent, intervals bracket their point estimate.
2. Pooling consistency: where a report carries per-fold detail AND a pooled
   figure, the pooled figure must equal the ratio-of-sums recomputation.
3. Cross-report agreement: quantities computed by more than one module (base
   rates, row counts) must agree exactly.
4. Prose drift: numbers asserted in Markdown tables are compared against the
   report they name.
5. Structural hygiene: Markdown section numbering is sequential, and every
   internal "section N" reference resolves to a section that exists.

Usage
-----
    python scripts/audit_reports.py            # report problems, exit 1 if any
    python scripts/audit_reports.py --verbose  # print every check performed
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"

# Tolerance for float comparisons. Reports round to ~4 significant figures in
# prose, so a relative tolerance of 1e-6 is tight enough to catch a genuine
# mismatch while ignoring JSON float round-tripping.
RTOL = 1e-6


class Findings:
    def __init__(self, verbose: bool = False) -> None:
        self.problems: list[str] = []
        self.checked = 0
        self.notes: list[str] = []
        self.verbose = verbose

    def note(self, message: str) -> None:
        """Record something worth printing that is not a failure.

        Used for known, explained gaps -- a report that predates provenance
        stamping and whose grid was established by other means. It is printed so
        the exception is visible rather than silently skipped.
        """
        self.notes.append(message)
        if self.verbose:
            print(f"  note  {message}")

    def check(self, ok: bool, message: str) -> bool:
        self.checked += 1
        if ok:
            if self.verbose:
                print(f"  ok    {message}")
        else:
            self.problems.append(message)
            print(f"  FAIL  {message}")
        return ok

    def close(self, a: float, b: float, *, rtol: float = RTOL) -> bool:
        if a is None or b is None:
            return False
        scale = max(abs(a), abs(b), 1e-12)
        return abs(a - b) / scale <= rtol


def load(name: str) -> dict | None:
    path = REPORTS / name
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"  FAIL  {name} is not valid JSON: {exc}")
        return None


# ---------------------------------------------------------------------------
# 1. Arithmetic inside a report
# ---------------------------------------------------------------------------
def check_arithmetic(f: Findings) -> None:
    print("\n[1] arithmetic inside each report")

    holdout = load("ml_final_holdout.json")
    if holdout:
        p, base, lift = (holdout.get("precision"), holdout.get("base_rate"),
                         holdout.get("lift"))
        f.check(f.close(p / base, lift),
                f"ml_final_holdout: lift {lift:.4f} == precision/base "
                f"{p / base:.4f}")
        sig, hits = holdout.get("signals"), holdout.get("hits")
        f.check(f.close(hits / sig, p),
                f"ml_final_holdout: hits/signals {hits / sig:.6f} == "
                f"precision {p:.6f}")
        lo, hi = holdout.get("date_clustered_95", [None, None])
        f.check(lo < p < hi,
                f"ml_final_holdout: date-clustered CI [{lo:.4f},{hi:.4f}] "
                f"brackets precision {p:.4f}")
        wlo, whi = holdout.get("wilson_95", [None, None])
        f.check(wlo < p < whi,
                f"ml_final_holdout: Wilson CI [{wlo:.4f},{whi:.4f}] "
                f"brackets precision {p:.4f}")

    ceiling = load("ml_precision_ceiling.json")
    if ceiling:
        rows, pos, base = (ceiling.get("oos_rows"), ceiling.get("oos_positives"),
                           ceiling.get("base_rate"))
        f.check(f.close(pos / rows, base),
                f"ml_precision_ceiling: {pos}/{rows} == base {base:.6f}")

    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        ranked = report.get("ranked") or []
        bad = [
            r["config"] for r in ranked
            if r.get("oos_base_rate") and r.get("oos_precision") is not None
            and not f.close(r["oos_precision"] / r["oos_base_rate"],
                            r.get("oos_lift", 0.0), rtol=1e-5)
        ]
        f.check(not bad,
                f"{name}: every row's lift == precision/base "
                f"({len(ranked)} rows{'' if not bad else ', bad: ' + str(bad[:3])})")


# ---------------------------------------------------------------------------
# 2. Pooled figures must equal the ratio-of-sums
# ---------------------------------------------------------------------------
def check_pooling(f: Findings) -> None:
    print("\n[2] pooled figures vs per-fold recomputation")
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        for r in report.get("ranked") or []:
            sig = r.get("per_fold_signals")
            pre = r.get("per_fold_oos")
            if not sig or not pre:
                continue
            total = sum(sig)
            if total == 0:
                continue
            recomputed = sum(p * n for p, n in zip(pre, sig)) / total
            if not f.check(f.close(recomputed, r["oos_precision"], rtol=1e-9),
                           f"{name}/{r['config']}: pooled precision "
                           f"{r['oos_precision']:.6f} == signal-weighted "
                           f"recomputation {recomputed:.6f}"):
                break


# ---------------------------------------------------------------------------
# 3. Quantities computed by more than one module must agree
# ---------------------------------------------------------------------------
def check_cross_report(f: Findings) -> None:
    print("\n[3] cross-report agreement")

    ceiling = load("ml_precision_ceiling.json")
    models = load("ml_search_models.json")
    if ceiling and models:
        # The ceiling module reports the pooled out-of-sample base rate
        # independently of the walk-forward module. Both now run on the full
        # session grid, so they must agree closely; a large mismatch means the
        # two disagree about which rows are out-of-sample, or that one report is
        # stale relative to the matrix on disk.
        pooled_base = ceiling.get("base_rate")
        configs = [r for r in (models.get("ranked") or [])
                   if r.get("config") == "fam_hgb_0"]
        if configs and pooled_base:
            got = configs[0]["oos_base_rate"]
            # The two modules drop different rows when fitting (the ceiling keeps
            # every scorable row; evaluate_fold requires resolved labels), so a
            # small difference is expected. A difference beyond ~0.5% relative
            # means they are not describing the same population.
            rel = abs(pooled_base - got) / max(pooled_base, 1e-12)
            f.check(rel < 5e-3,
                    f"base rate agrees across modules within 0.5%: ceiling "
                    f"{pooled_base:.6f} vs walkforward {got:.6f} "
                    f"(rel {rel*100:.3f}%)")

    # ------------------------------------------------------------------
    # Published CSVs, which nothing checked until now.
    #
    # The audit read only JSON, so every CSV in reports/ was unverified -- and
    # the two hit-rate files count signals differently in a way that is easy to
    # get wrong: README documents that the tradeability file's larger count is
    # the raw count plus the censored windows, while `unfillable` is a different,
    # smaller subset. That is exactly the kind of claim that should be executable
    # rather than prose.
    # ------------------------------------------------------------------
    import csv as _csv

    def load_csv(name: str) -> list[dict]:
        path = REPORTS / name
        if not path.exists():
            return []
        with path.open(encoding="utf-8", newline="") as fh:
            return list(_csv.DictReader(fh))

    hit = {r["strategy_id"]: r for r in load_csv("hitrate_vs_expectancy.csv")}
    trade = {r["label"]: r for r in load_csv("tradeability_by_strategy.csv")}
    raw = {r["strategy_id"]: r for r in load_csv("webpro_hit_rates.csv")}
    if hit and trade and raw:
        shared = sorted(set(hit) & set(trade))
        f.check(len(shared) > 0,
                f"hit-rate and tradeability CSVs share strategies ({len(shared)})")
        # identical sets of strategies, and the documented arithmetic relation
        f.check(set(hit) <= set(raw),
                "every strategy in hitrate_vs_expectancy.csv has a row in "
                "webpro_hit_rates.csv")
        bad_relation = []
        for sid in shared:
            expected = (int(raw[sid]["signals_raw__webpro"])
                        + int(raw[sid]["censored_signals__webpro"]))
            if int(trade[sid]["signals"]) != expected:
                bad_relation.append(sid)
        f.check(not bad_relation,
                f"tradeability signals == raw + censored for every shared strategy "
                f"({len(bad_relation)} violate: {bad_relation[:4]})")
        # `unfillable` must be a subset of the counted signals, and never equal
        # the raw/censored difference (the two are different quantities and the
        # prose says so).
        over = [s for s in shared
                if int(trade[s]["unfillable"]) > int(trade[s]["signals"])]
        f.check(not over, f"unfillable never exceeds signals ({over[:4]})")
        mism = [s for s in shared
                if int(hit[s]["signals"]) != int(raw[s]["signals_raw__webpro"])]
        f.check(not mism,
                f"hitrate_vs_expectancy signals == raw webpro signals "
                f"({len(mism)} differ: {mism[:4]})")
        # A hit rate must be a proportion of its own denominator.
        bad_rate = []
        for sid, row in hit.items():
            try:
                n, rate = int(row["signals"]), float(row["hit_rate"])
            except (TypeError, ValueError):
                continue
            if n and not (0.0 <= rate <= 1.0):
                bad_rate.append(sid)
        f.check(not bad_rate,
                f"hit rates lie in [0,1] ({bad_rate[:4]})")

    if f.verbose:
        print("  (checked the published CSV denominators)")

    # ------------------------------------------------------------------
    # live_readiness.json -- the report that answers "can this be traded at
    # all?", and previously no check read it.
    # ------------------------------------------------------------------
    lr = load("live_readiness.json")
    if lr:
        rows = lr.get("expectancy") or []
        f.check(bool(rows), f"live_readiness carries expectancy rows ({len(rows)})")
        for row in rows:
            label = row.get("label", "?")
            cost = row.get("cost_bps_round_trip")
            gross, net = row.get("gross_mean_return"), row.get("net_mean_return")
            if cost is not None and gross is not None and net is not None:
                # Net must be gross less the stated round-trip cost. This is the
                # report's central arithmetic claim and nothing verified it.
                expected = gross - float(cost) / 10_000.0
                f.check(
                    abs(net - expected) < 1e-9,
                    f"live_readiness '{label}': net {net:.6f} == gross {gross:.6f} "
                    f"- {cost}bp ({expected:.6f})",
                )
            sig, res = row.get("signals"), row.get("resolved")
            if sig is not None and res is not None:
                f.check(
                    int(res) <= int(sig),
                    f"live_readiness '{label}': resolved {res} <= signals {sig}",
                )
            a, b = row.get("net_p10"), row.get("net_p90")
            if a is not None and b is not None:
                f.check(a <= b,
                        f"live_readiness '{label}': net_p10 {a:.4f} <= net_p90 {b:.4f}")
        intrad = lr.get("intraday") or {}
        f.check(bool(intrad), "live_readiness carries the intraday assessment")

    # ------------------------------------------------------------------
    # lowzone_hit_rates.csv and webpro_scan_summary.json.
    #
    # The low-zone table is the V0x family's published hit-rate ledger, and its
    # "in_sample" flag is what stops an in-sample fit from being read as a live
    # result -- so an out-of-sample row whose precision exceeds its own Wilson
    # upper bound, or a lift that disagrees with precision / baseline, means the
    # table no longer says what the documents claim it says.
    # ------------------------------------------------------------------
    lz = load_csv("lowzone_hit_rates.csv")
    if lz:
        f.check(True, f"lowzone_hit_rates.csv parses ({len(lz)} rows)")
        bad_lift, bad_ci, bad_frac = [], [], []
        for row in lz:
            rid = f"{row.get('version')}/{row.get('regime')}"
            try:
                prec = float(row["bull_precision"])
                base = float(row["baseline_rate"])
                lift = float(row["lift_vs_baseline"])
                lo, hi = float(row["wilson_low"]), float(row["wilson_high"])
            except (KeyError, TypeError, ValueError):
                continue
            if base > 0 and abs(lift - prec / base) > 1e-3:
                bad_lift.append((rid, lift, prec / base))
            if not (0.0 <= lo <= prec <= hi <= 1.0):
                bad_ci.append((rid, lo, prec, hi))
            if not (0.0 <= prec <= 1.0):
                bad_frac.append(rid)
        f.check(not bad_lift,
                f"lowzone lift == precision / baseline ({len(bad_lift)} differ: "
                f"{bad_lift[:3]})")
        f.check(not bad_ci,
                f"lowzone Wilson bound brackets the precision ({len(bad_ci)} "
                f"violate: {bad_ci[:3]})")
        f.check(not bad_frac, f"lowzone precisions are proportions ({bad_frac[:3]})")

    scan = load("webpro_scan_summary.json")
    if scan:
        # The scan's own signal count must equal the headline figure the hit-rate
        # table reports for the same population; they are produced by the same
        # pass and drifted apart once already.
        emitted = scan.get("signals_emitted")
        f.check(isinstance(emitted, int) and emitted > 0,
                f"webpro_scan_summary reports signals_emitted ({emitted})")
        if raw:
            total = sum(int(r["signals_raw__webpro"]) for r in raw.values())
            f.check(
                total <= (emitted or 0),
                f"per-strategy raw webpro signals {total:,} do not exceed the scan "
                f"total {emitted:,}",
            )
        f.check(scan.get("stride") is not None,
                "webpro_scan_summary records its stride")


    # Every report that carries a base rate must agree on which grid it came
    # from. Mixing grids silently is the failure mode that produced the stale
    # 15.98% in an earlier revision of the documents.
    #
    # Compare the MEDIAN base rate over configs that completed every fold and saw
    # a non-trivial number of signals. An earlier version compared each report's
    # top-level `oos_base_rate` field, which raised a false alarm: a report's
    # most precise config can be a degenerate one that completed only 2 of 4
    # folds, so its base rate describes those two folds rather than the grid.
    full_fold_bases: dict[str, float] = {}
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        rows = [r for r in (report.get("ranked") or [])
                if r.get("n_folds", 0) >= 4 and r.get("oos_signals", 0) >= 100
                and r.get("oos_base_rate")]
        if rows:
            full_fold_bases[name] = float(
                statistics.median([r["oos_base_rate"] for r in rows])
            )
    if len(full_fold_bases) > 1:
        vals = list(full_fold_bases.values())
        spread = max(vals) - min(vals)
        # The tolerance has to be tighter than the difference it is meant to
        # detect. On one matrix the same label and fold count give a base rate
        # that is bit-identical across configurations, so the only reason two
        # full-fold rows differ is that they came from different matrices -- and
        # the two grids in play differ by 1.644e-05 (0.040894451 dense vs
        # 0.040878010 stride-5). The previous 5e-4 tolerance was 30x too loose
        # and would have accepted a report mixing the two.
        f.check(spread < 1e-8,
                f"search reports share one grid: median base rate over full-fold "
                f"configs spans {spread:.3e} "
                f"({ {k: round(v, 11) for k, v in full_fold_bases.items()} })")

    # A single report must not MIX grids. The check above compares reports to
    # each other via a median, which is blind to one report containing rows from
    # two grids: ml_search_wide.json carried 21 rows at 0.0264875 (label_close)
    # and 29 at 0.04087801 (label_high on the stride-5 matrix) at the same time,
    # and the median simply picked one. Rows with the same label and the same
    # completed-fold count on one matrix must share a base rate exactly; a
    # spread within such a group means the report was assembled from different
    # runs or different matrices.
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        groups: dict[tuple, set[float]] = {}
        for r in (report.get("ranked") or []):
            base = r.get("oos_base_rate")
            if not base or r.get("n_folds", 0) < 4 or r.get("oos_signals", 0) < 100:
                continue
            groups.setdefault((r.get("label"), r.get("n_folds")), set()).add(
                round(float(base), 8)
            )
        for (label, n_folds), bases in sorted(groups.items(), key=str):
            f.check(
                len(bases) == 1,
                f"{name}: rows with label={label} and {n_folds} completed folds "
                f"share one base rate (found {sorted(bases)})",
            )

    # ------------------------------------------------------------------
    # Baseline provenance.
    #
    # `reports/webpro_baselines.json` and `reports/lowzone_baselines.json` both
    # publish a field called `bull_rate` for the same three regimes and they
    # disagree (webpro 3.0348% vs 3.0893%, low504 4.6956% vs 4.2099%), because
    # `scan_all` counts the scanned grid (min_history plus stride) while
    # `backtest_lowzone` counts every resolved bar.
    #
    # This looked like a defect and was reported as one -- "low504 z=+11.50, not
    # noise". It is not: that z treats 2.68M dependent panel rows as independent
    # draws. With market dates as clusters the same contrast is z=+1.24,
    # bootstrap p=0.22. The gap is a legitimate population difference (the
    # `_seq >= 60` warm-up filter is also a calendar filter), and no published
    # lift is wrong, because each family already divides by its OWN baseline.
    #
    # So the invariant to enforce is not that the two agree -- it is that each
    # says which population it measured, and that the ML reports' third
    # population is not confused with either. Without this, a future reader
    # repeats exactly the analysis above and reaches the wrong conclusion.
    # ------------------------------------------------------------------
    for name, expect_id in (("webpro_baselines.json", "scanned"),
                            ("lowzone_baselines.json", "panel")):
        report = load(name)
        if not report:
            continue
        for regime, entry in report.items():
            if not isinstance(entry, dict) or "bull_rate" not in entry:
                continue
            pop = entry.get("population")
            if pop is None:
                # The reports predate the provenance fields; regeneration is
                # pending. Skipping silently would hide that the guard is not yet
                # doing anything, so the gap is counted and named.
                f.note(f"{name}:{regime} carries no `population` block yet, so its "
                       f"base rate is not labelled as the {expect_id!r} population; "
                       f"regenerate to arm this check")
                continue
            pid = pop.get("population_id") if isinstance(pop, dict) else pop
            f.check(
                pid == expect_id,
                f"{name}:{regime} labels its base rate as the {expect_id!r} "
                f"population (found {pid!r})",
            )
            rows = entry.get("candidates") or entry.get("evaluated_points")
            if isinstance(pop, dict) and pop.get("rows") and rows:
                f.check(
                    int(pop["rows"]) == int(rows),
                    f"{name}:{regime} population rows {pop['rows']:,} matches "
                    f"the published denominator {int(rows):,}",
                )

    # The ML reports measure a THIRD population (walk-forward folds on the
    # feature matrix), and quoting its base rate beside either file above is a
    # category error. Flag the value if it appears unresolved in prose.
    ml_base = (load("ml_precision_ceiling.json") or {}).get("base_rate")
    if ml_base:
        for doc in ("README.md", "TARGET_70PCT.md"):
            path = ROOT / doc
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            if f"{ml_base*100:.4f}" in text or f"{ml_base*100:.2f}" in text:
                f.check(
                    bool(re.search(r"(walk-forward|fold|ML|feature matrix)", text)),
                    f"{doc} quotes the ML base rate {ml_base*100:.4f}% and says "
                    f"which population it belongs to",
                )

    # Every matrix the reports could have come from, keyed by stride. Checking
    # only `s5` was a dead guard: the holdout module writes
    # `n_train_rows`/`n_holdout_rows` but this check read
    # `train_rows`/`holdout_rows`, so both `.get()` calls returned None, the
    # `if` was False, and the check NEVER RAN while still being counted as a
    # pass. A holdout report that had silently regressed to a different grid
    # went undetected for exactly this reason.
    matrices: dict[int, dict] = {}
    for path in sorted((ROOT / "outputs" / "ml").glob("matrix_*_meta.json")):
        try:
            meta = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            f.check(False, f"{path.name} parses: {exc}")
            continue
        meta["_name"] = path.name
        f.check(meta.get("features") == 82,
                f"{path.name} advertises 82 features (found {meta.get('features')})")
        if meta.get("stride") is not None:
            matrices[int(meta["stride"])] = meta

    f.check(bool(matrices), "at least one feature matrix is present on disk")

    holdout = load("ml_final_holdout.json")
    if holdout:
        train_n = holdout.get("n_train_rows")
        hold_n = holdout.get("n_holdout_rows")
        # Missing keys are now a FAILURE, not a silent pass. This is the whole
        # point: a renamed field must break the check loudly.
        f.check(
            train_n is not None and hold_n is not None,
            f"holdout report carries n_train_rows/n_holdout_rows "
            f"(found {train_n!r}/{hold_n!r})",
        )
        stride = holdout.get("stride")
        f.check(stride is not None, "holdout report records the stride it used")
        if train_n is not None and hold_n is not None and stride is not None:
            # Match the holdout against the matrix for ITS OWN stride. Comparing
            # it against every matrix on disk is wrong: the stride-1 holdout
            # legitimately does not fit the stride-5 matrix, and those are both
            # valid artifacts serving different purposes.
            meta = matrices.get(int(stride))
            f.check(
                meta is not None,
                f"a matrix exists for the holdout's stride {stride} "
                f"(found strides {sorted(matrices)})",
            )
            if meta is not None:
                f.check(
                    train_n + hold_n <= meta["rows"],
                    f"holdout split {train_n:,}+{hold_n:,} fits within "
                    f"{meta['_name']} ({meta['rows']:,} rows, stride {stride})",
                )


# ---------------------------------------------------------------------------
# 4. Prose drift: numbers in Markdown vs the reports they cite
# ---------------------------------------------------------------------------
def extract_table_cells(text: str) -> list[str]:
    cells: list[str] = []
    for line in text.splitlines():
        if line.count("|") >= 2:
            cells.extend(c.strip() for c in line.split("|") if c.strip())
    return cells


def check_prose(f: Findings, verbose: bool) -> None:
    print("\n[4] prose drift against reports")

    holdout = load("ml_final_holdout.json")
    ceiling = load("ml_precision_ceiling.json")
    if not (holdout and ceiling):
        print("  (skipped: reports missing)")
        return

    # ------------------------------------------------------------------
    # Every report that a grid could shift must say which grid it used.
    #
    # Two grids are in circulation and they give different base rates
    # (0.04089445 dense vs 0.04087801 stride-5), so a report without a `stride`
    # field cannot be compared with anything. Skipping a report because it
    # happens to predate the stamping is how the gap stayed invisible, so the
    # reports that genuinely lack the field are named individually with the grid
    # they were measured on, established from their own payload.
    # ------------------------------------------------------------------
    known_grid = {
        # n_rows 281,227 and oos_base_rate 0.04087801 = the stride-5 matrix.
        "ml_crosssec_final.json": ("stride-5", "n_rows=281,227, base=0.04087801"),
        "ml_crosssec_hgb0.json": ("stride-5", "same run as ml_crosssec_final"),
        # These three were regenerated on the dense grid but by a run whose code
        # predated the provenance stamp, so the numbers are right and the grid is
        # provable from the payload while the `stride` field is absent. They are
        # listed and then scheduled for regeneration, not exempted permanently.
        "ml_search_models.json": ("stride-1", "median full-fold base=0.04089445"),
        "ml_search_ablation.json": ("stride-1", "median full-fold base=0.04089445"),
        "ml_null_tests.json": ("stride-1", "n_rows=2,680,715 = the dense matrix"),
    }
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json", "ml_crosssec_final.json",
                 "ml_crosssec_hgb0.json", "ml_precision_ceiling.json",
                 "ml_null_tests.json", "ml_concentration.json"):
        report = load(name)
        if not report:
            continue
        stride = report.get("stride")
        if stride is None and name in known_grid:
            grid, why = known_grid[name]
            f.note(f"{name} has no `stride` field but is {grid} ({why}); "
                   f"regenerate to stamp it")
            continue
        f.check(stride is not None,
                f"{name} records the stride it was measured on")

    #
    # The previous version only grepped for literal strings ("13.61" in the
    # document). That is blind in the one direction that counts: prose asserting
    # 13.61% passed while reports/ml_final_holdout.json said 11.05%, because the
    # check never compared the two. A published report silently regressed to a
    # different grid and 107 checks still reported "0 problems".
    #
    # So: derive the expected strings FROM THE REPORT and require the documents
    # to agree. If the report changes, the documents must change with it or this
    # fails.
    # ------------------------------------------------------------------
    holdout = load("ml_final_holdout.json")
    ceiling = load("ml_precision_ceiling.json")
    if not holdout:
        f.check(False, "ml_final_holdout.json present and parseable")
        return

    if holdout:
        pct = holdout["precision"] * 100
        lift = holdout["lift"]
        # Accept either one or two decimal places in prose.
        precision_variants = {f"{pct:.1f}", f"{pct:.2f}"}
        lift_variants = {f"{lift:.1f}", f"{lift:.2f}"}
        signals_variants = {f"{holdout['signals']:,}", str(holdout["signals"])}
        for doc in ("README.md", "TARGET_70PCT.md"):
            path = ROOT / doc
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            # The holdout precision must appear somewhere in each headline doc.
            f.check(
                any(v in text for v in precision_variants),
                f"{doc} states the holdout precision {pct:.2f}% "
                f"(report says {holdout['precision']:.6f})",
            )
            f.check(
                any(v in text for v in lift_variants),
                f"{doc} states the holdout lift {lift:.2f}x "
                f"(report says {holdout['lift']:.6f})",
            )
            # And must NOT still assert a superseded holdout precision, unless
            # the line is recording that history. Correction blocks are how this
            # document legitimately explains the 12.14% -> 11.05% -> 13.61%
            # chain, so blockquotes and fenced code are exempt; a bare claim in
            # body text is not.
            stale = {12.14, 11.05, 13.61} - {round(pct, 2)}
            in_fence = False
            for line_no, line in enumerate(text.splitlines(), 1):
                stripped = line.lstrip()
                if stripped.startswith("```"):
                    in_fence = not in_fence
                    continue
                if in_fence or stripped.startswith(">"):
                    continue
                window = "\n".join(
                    text.splitlines()[max(0, line_no - 7):line_no]
                )
                if re.search(r"(correct|retired|earlier|previous|was reported|"
                             r"supersed|revision|history|before the|changed|"
                             r"old stride)", line + window, re.I):
                    continue
                for value in stale:
                    if re.search(rf"\b{value:.2f}\s*%", line):
                        f.check(
                            False,
                            f"{doc}:{line_no} asserts holdout precision "
                            f"{value:.2f}%, superseded; report says {pct:.2f}%",
                        )

    if verbose:
        print(f"  (checked headline figures against the payload)")

    # ------------------------------------------------------------------
    # Tie the headline tables to their reports.
    #
    # Grepping a document for a literal ("13.61") only proves the document
    # contains that string; it cannot prove the string is still TRUE. These
    # checks parse the table rows and require each configuration's numbers to
    # exist in the report the prose says they came from. When ml_search_wide.json
    # is regenerated on a different grid, its cited table must be updated with it
    # or this fails.
    # ------------------------------------------------------------------
    def table_rows(doc: str, header_needle: str) -> list[list[str]]:
        """Data rows of the first Markdown table under a header line."""
        path = ROOT / doc
        if not path.exists():
            return []
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            if header_needle not in line:
                continue
            rows: list[list[str]] = []
            for follow in lines[i + 1:]:
                if follow.strip().startswith("|"):
                    cells = [c.strip() for c in follow.strip().strip("|").split("|")]
                    if cells and not set("".join(cells)) <= set("-: "):
                        rows.append(cells)
                elif rows:
                    break
            if rows:
                return rows
        return []

    def pct(cell: str) -> float | None:
        m = re.search(r"([0-9]+(?:\.[0-9]+)?)\s*%", cell)
        return float(m.group(1)) if m else None

    def count(cell: str) -> int | None:
        m = re.search(r"([0-9][0-9,]*)\s*$", cell.replace("**", "").strip())
        return int(m.group(1).replace(",", "")) if m else None

    wide = load("ml_search_wide.json")
    if wide:
        ranked = wide.get("ranked") or []
        by_sig = {r.get("oos_signals"): r for r in ranked}
        # Column layout: Configuration | In-sample | Out-of-sample | Signals | Folds
        for cells in table_rows("TARGET_70PCT.md", "showing **both** numbers"):
            if len(cells) < 4:
                continue
            ins, oos, sig = pct(cells[1]), pct(cells[2]), count(cells[3])
            if oos is None or sig is None:
                continue
            row = by_sig.get(sig)
            if row is None:
                f.check(False,
                        f"TARGET_70PCT.md §4 cites {sig:,} signals, which is in no "
                        f"ml_search_wide.json row")
                continue
            f.check(
                abs(row["oos_precision"] * 100 - oos) < 0.005,
                f"TARGET_70PCT.md §4 says {sig:,} signals score {oos:.2f}% OOS; "
                f"the report says {row['oos_precision']*100:.2f}%",
            )
            if ins is not None:
                f.check(
                    abs(row["insample_precision"] * 100 - ins) < 0.005,
                    f"TARGET_70PCT.md §4 says {sig:,} signals were {ins:.2f}% "
                    f"in-sample; the report says "
                    f"{row['insample_precision']*100:.2f}%",
                )

    models = load("ml_search_models.json")
    if models:
        by_name = {r["config"]: r for r in (models.get("ranked") or [])}
        # README's table mixes the four fitted families with rows sourced from
        # other reports (the per-fold oracle, the top-1-per-session experiment,
        # the one-shot holdout). Only the family rows belong to this report, so
        # scope the check to rows that actually name a family.
        family_words = ("Random Forest", "HGB", "ExtraTrees", "Logistic",
                        "Gradient Boosting")
        for cells in table_rows("README.md", "| Configuration | In-sample |"):
            if len(cells) < 4:
                continue
            if not any(w.lower() in cells[0].lower() for w in family_words):
                continue
            ins, oos, sig = pct(cells[1]), pct(cells[2]), count(cells[3])
            if None in (ins, oos, sig):
                continue
            match = [r for r in by_name.values()
                     if r.get("oos_signals") == sig
                     and abs(r["oos_precision"] * 100 - oos) < 0.005]
            f.check(bool(match),
                    f"README.md family row '{cells[0]}' ({ins}% in / {oos}% OOS "
                    f"/ {sig:,} signals) exists in ml_search_models.json")

    # The 2026-holdout treatment table. It sat on a superseded run (8,352 signals
    # at 12.07%) because the counts it quoted were printed to stdout and never
    # stored. Now that the report carries {precision, signals} per treatment, the
    # table can be verified cell by cell.
    conc = load("ml_concentration.json")
    if conc and (conc.get("holdout") or {}).get("drop_top_dates"):
        ho = conc["holdout"]
        wanted = {"As published": 0, "Drop busiest date": 1,
                  "Drop 3 busiest dates": 3, "Drop 5 busiest dates": 5,
                  "Drop 10 busiest dates": 10}
        drops = {int(k): v for k, v in ho["drop_top_dates"].items()
                 if isinstance(v, dict)}
        for cells in table_rows("TARGET_70PCT.md", "**2026 holdout, same treatment"):
            if len(cells) < 3:
                continue
            label = cells[0]
            got_p, got_n = pct(cells[1]), count(cells[2])
            n_drop = wanted.get(label)
            if n_drop is None or n_drop not in drops or got_p is None:
                # Half-sample rows are checked against the halves below.
                if label.startswith("First half") and got_p is not None:
                    f.check(
                        abs(ho["first_half_precision"] * 100 - got_p) < 0.005,
                        f"TARGET_70PCT.md says first half {got_p:.2f}%; report "
                        f"says {ho['first_half_precision']*100:.2f}%")
                elif label.startswith("Second half") and got_p is not None:
                    f.check(
                        abs(ho["second_half_precision"] * 100 - got_p) < 0.005,
                        f"TARGET_70PCT.md says second half {got_p:.2f}%; report "
                        f"says {ho['second_half_precision']*100:.2f}%")
                continue
            row = drops[n_drop]
            f.check(
                abs(row["precision"] * 100 - got_p) < 0.005,
                f"TARGET_70PCT.md says '{label}' is {got_p:.2f}%; the report "
                f"says {row['precision']*100:.2f}%",
            )
            if got_n is not None:
                f.check(
                    row["signals"] == got_n,
                    f"TARGET_70PCT.md says '{label}' leaves {got_n:,} signals; "
                    f"the report says {row['signals']:,}",
                )

    if verbose:
        print("  (tied headline tables to their source reports)")

    # Retired figures, kept with the reason so the list doubles as a record of
    # corrections rather than a mystery. Only values that are retired in EVERY
    # context belong here; a value that is still current somewhere (15.98% is
    # the live walk-forward baseline) must not, or the check cries wolf and gets
    # switched off.
    retired = {
        "20.23": "precision ceiling before the frontier grid was densified",
        "3.87": "lift computed against an unweighted-mean base rate",
        "3.58": "lift computed against a signal-weighted base rate",
        "24.54": "frontier computed on the stride-5 grid",
    }
    exempt_markers = re.compile(
        r"(correct|retired|earlier|previous|was reported|not the|superseded|"
        r"original|first \"?fix)",
        re.I,
    )
    prose_docs = ["README.md", "TARGET_70PCT.md", "RESULTS.md"]
    for doc in prose_docs:
        path = ROOT / doc
        if not path.exists():
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_no, line in enumerate(lines, 1):
            window = "\n".join(lines[max(0, line_no - 7):line_no])
            if exempt_markers.search(line) or exempt_markers.search(window):
                continue
            for value, why in retired.items():
                if re.search(rf"\b{re.escape(value)}\s*(x|×)", line):
                    f.check(False, f"{doc}:{line_no} asserts lift {value}x, "
                                   f"retired because {why}")
            if re.search(r"ceiling[^|]*\b20\.23\b", line, re.I):
                f.check(False, f"{doc}:{line_no} asserts a 20.23 ceiling, "
                               f"retired because {why}")

    if verbose:
        print(f"  (scanned {len(prose_docs)} documents for retired figures)")


# ---------------------------------------------------------------------------
# 5. Markdown structure
# ---------------------------------------------------------------------------
def check_markdown_structure(f: Findings) -> None:
    print("\n[5] markdown structure")
    for doc in ("README.md", "TARGET_70PCT.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()

        numbers = []
        for line in lines:
            m = re.match(r"^## (\d+)\.", line)
            if m:
                numbers.append((int(m.group(1)), line.strip()))
        expected = list(range(1, len(numbers) + 1))
        got = [n for n, _ in numbers]
        f.check(got == expected,
                f"{doc}: sections numbered 1..{len(numbers)} with no gaps or "
                f"duplicates (found {got})")

        # Every "section N" / "§N" reference must resolve.
        valid = set(got)
        dangling = []
        for line_no, line in enumerate(lines, 1):
            for m in re.finditer(r"§(\d+)", line):
                ref = int(m.group(1))
                if ref not in valid:
                    dangling.append(f"line {line_no} -> §{ref}")
        f.check(not dangling,
                f"{doc}: all §-references resolve"
                f"{'' if not dangling else ' (' + '; '.join(dangling[:4]) + ')'}")

    # Relative Markdown links must point at files that exist.
    link_re = re.compile(r"\[[^\]]+\]\(([^)#][^)]*)\)")
    for doc in ("README.md", "TARGET_70PCT.md", "RESULTS.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        missing = []
        for target in link_re.findall(path.read_text(encoding="utf-8")):
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            if not (ROOT / target.split("#")[0]).exists():
                missing.append(target)
        f.check(not missing,
                f"{doc}: relative links resolve"
                f"{'' if not missing else ' (missing: ' + str(missing[:4]) + ')'}")


# ---------------------------------------------------------------------------
# 6. Reported commit must match the tree
# ---------------------------------------------------------------------------
def check_no_orphan_reports(f: Findings) -> None:
    print("\n[6] report inventory")
    on_disk = {p.name for p in REPORTS.glob("*.json")}
    csvs = {p.name for p in REPORTS.glob("*.csv")}
    print(f"  ({len(on_disk)} JSON reports, {len(csvs)} CSVs present)")
    for name in sorted(on_disk):
        load(name)  # surface JSON errors early
    f.check(True, f"{len(on_disk)} reports parse")

    # Which published artifacts does this audit actually read? A report that no
    # check names is published and unverified, which is how nine of them --
    # including live_readiness.json, which carries the intraday answer -- sat
    # outside every check while the audit reported no problems. This check does
    # not verify their contents; it makes their absence from the audit visible.
    src = Path(__file__).read_text(encoding="utf-8")
    referenced = set(re.findall(r"[\"']([A-Za-z0-9_]+\.(?:json|csv))[\"']", src))
    unreferenced = sorted((on_disk | csvs) - referenced)
    for name in unreferenced:
        f.note(f"reports/{name} is published but no check reads it")
    print(f"  ({len(unreferenced)} published artifact(s) outside every check)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verbose", action="store_true",
                    help="print every check, not only failures")
    args = ap.parse_args()

    print(f"auditing reports in {REPORTS}")
    f = Findings(verbose=args.verbose)
    check_arithmetic(f)
    check_pooling(f)
    check_cross_report(f)
    check_prose(f, args.verbose)
    check_markdown_structure(f)
    check_no_orphan_reports(f)

    print("\n" + "=" * 70)
    print(f"{f.checked} checks run, {len(f.problems)} problem(s)")
    for p in f.problems:
        print(f"  - {p}")
    if f.notes:
        print(f"\n{len(f.notes)} known gap(s), reported but not failures:")
        for n in f.notes:
            print(f"  - {n}")
    return 1 if f.problems else 0


if __name__ == "__main__":
    sys.exit(main())
