"""Audit the published reports and documents for internal consistency.

This repository publishes numbers in three places that can drift apart:

* ``reports/*.json`` — machine-readable ground truth, regenerated by the ``src``
  and ``src.ml`` modules;
* the Markdown documents (``README.md``, ``TARGET_70PCT.md``, ``RESULTS.md``);
* the audit documents under ``audit/``.

Nothing previously checked that a figure quoted in prose still matched the report
it came from. That gap has already produced two real defects in this project: a
precision ceiling quoted as 20.23% after the grid was densified, and a lift
quoted as 3.87x then "corrected" to 3.58x when the exact pooled value is 3.91x.
Both were found by hand, late. This module finds that class of error
mechanically.

Checks performed
----------------
1. Arithmetic inside each report: lift equals precision divided by base rate,
   signal and hit counts are consistent, intervals bracket their point estimate.
2. Pooling consistency: where a report carries per-fold detail AND a pooled
   figure, the pooled figure must equal the ratio-of-sums recomputation.
3. Cross-report agreement: quantities computed by more than one module (base
   rates, row counts) must agree exactly.
4. Prose drift: numbers asserted in Markdown tables are compared against the
   report they name.
5. Structural hygiene: Markdown section numbering is sequential, and every
   internal "section N" reference resolves to a section that exists.

Usage
-----
    python scripts/audit_reports.py            # report problems, exit 1 if any
    python scripts/audit_reports.py --verbose  # print every check performed
"""

from __future__ import annotations

import argparse
import csv as _csv
import json
import re
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"

# Tolerance for float comparisons. Reports round to ~4 significant figures in
# prose, so a relative tolerance of 1e-6 is tight enough to catch a genuine
# mismatch while ignoring JSON float round-tripping.
RTOL = 1e-6


class Findings:
    def __init__(self, verbose: bool = False) -> None:
        self.problems: list[str] = []
        self.checked = 0
        self.notes: list[str] = []
        self.verbose = verbose

    def note(self, message: str) -> None:
        """Record something worth printing that is not a failure.

        Used for known, explained gaps -- a report that predates provenance
        stamping and whose grid was established by other means. It is printed so
        the exception is visible rather than silently skipped.
        """
        self.notes.append(message)
        if self.verbose:
            print(f"  note  {message}")

    def check(self, ok: bool, message: str) -> bool:
        self.checked += 1
        if ok:
            if self.verbose:
                print(f"  ok    {message}")
        else:
            self.problems.append(message)
            print(f"  FAIL  {message}")
        return ok

    def close(self, a: float, b: float, *, rtol: float = RTOL) -> bool:
        if a is None or b is None:
            return False
        scale = max(abs(a), abs(b), 1e-12)
        return abs(a - b) / scale <= rtol


# Load failures are recorded here rather than printed and forgotten. `load` and
# `load_csv` are called from module-level helpers that have no `Findings` handle,
# so an unreadable report used to print a FAIL line and then vanish: every check
# gated on that report simply skipped, the problem list stayed empty, and the
# process exited 0. A truncated file mid-regeneration is exactly that state, so
# the audit went green precisely when a report was unusable. main() folds this
# list into the reported problems.
LOAD_ERRORS: list[str] = []


def load(name: str) -> dict | None:
    path = REPORTS / name
    if not path.exists():
        # A report named by the audit but absent is a finding, not a reason to
        # skip: silently skipping is how a deleted artifact passes.
        LOAD_ERRORS.append(f"reports/{name} is referenced by the audit but missing")
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        LOAD_ERRORS.append(f"reports/{name} is not readable JSON: {exc}")
        return None


def load_csv(name: str) -> list[dict]:
    """Read a published CSV from reports/ as a list of dicts.

    Module-level rather than a closure inside check_arithmetic: check_frontier
    and any later check need it too, and a name that only exists inside one
    function is invisible from the next.
    """
    path = REPORTS / name
    if not path.exists():
        LOAD_ERRORS.append(f"reports/{name} is referenced by the audit but missing")
        return []
    with path.open(encoding="utf-8", newline="") as fh:
        return list(_csv.DictReader(fh))


def _num(value: object) -> float | None:
    """Parse a CSV cell as a float, or None if it is not numeric."""
    try:
        return float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# 1. Arithmetic inside a report
# ---------------------------------------------------------------------------
def check_arithmetic(f: Findings) -> None:
    print("\n[1] arithmetic inside each report")

    holdout = load("ml_final_holdout.json")
    if holdout:
        p, base, lift = (holdout.get("precision"), holdout.get("base_rate"),
                         holdout.get("lift"))
        f.check(f.close(p / base, lift),
                f"ml_final_holdout: lift {lift:.4f} == precision/base "
                f"{p / base:.4f}")
        sig, hits = holdout.get("signals"), holdout.get("hits")
        f.check(f.close(hits / sig, p),
                f"ml_final_holdout: hits/signals {hits / sig:.6f} == "
                f"precision {p:.6f}")
        lo, hi = holdout.get("date_clustered_95", [None, None])
        f.check(lo < p < hi,
                f"ml_final_holdout: date-clustered CI [{lo:.4f},{hi:.4f}] "
                f"brackets precision {p:.4f}")
        wlo, whi = holdout.get("wilson_95", [None, None])
        f.check(wlo < p < whi,
                f"ml_final_holdout: Wilson CI [{wlo:.4f},{whi:.4f}] "
                f"brackets precision {p:.4f}")

    ceiling = load("ml_precision_ceiling.json")
    if ceiling:
        rows, pos, base = (ceiling.get("oos_rows"), ceiling.get("oos_positives"),
                           ceiling.get("base_rate"))
        f.check(f.close(pos / rows, base),
                f"ml_precision_ceiling: {pos}/{rows} == base {base:.6f}")

    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        ranked = report.get("ranked") or []
        bad = [
            r["config"] for r in ranked
            if r.get("oos_base_rate") and r.get("oos_precision") is not None
            and not f.close(r["oos_precision"] / r["oos_base_rate"],
                            r.get("oos_lift", 0.0), rtol=1e-5)
        ]
        f.check(not bad,
                f"{name}: every row's lift == precision/base "
                f"({len(ranked)} rows{'' if not bad else ', bad: ' + str(bad[:3])})")


# ---------------------------------------------------------------------------
# 2. Pooled figures must equal the ratio-of-sums
# ---------------------------------------------------------------------------
def check_pooling(f: Findings) -> None:
    print("\n[2] pooled figures vs per-fold recomputation")
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        for r in report.get("ranked") or []:
            sig = r.get("per_fold_signals")
            pre = r.get("per_fold_oos")
            if not sig or not pre:
                continue
            total = sum(sig)
            if total == 0:
                continue
            recomputed = sum(p * n for p, n in zip(pre, sig)) / total
            if not f.check(f.close(recomputed, r["oos_precision"], rtol=1e-9),
                           f"{name}/{r['config']}: pooled precision "
                           f"{r['oos_precision']:.6f} == signal-weighted "
                           f"recomputation {recomputed:.6f}"):
                break


# ---------------------------------------------------------------------------
# 3. Quantities computed by more than one module must agree
# ---------------------------------------------------------------------------
def check_cross_report(f: Findings) -> None:
    print("\n[3] cross-report agreement")

    ceiling = load("ml_precision_ceiling.json")
    models = load("ml_search_models.json")
    if ceiling and models:
        # The ceiling module reports the pooled out-of-sample base rate
        # independently of the walk-forward module. Both now run on the full
        # session grid, so they must agree closely; a large mismatch means the
        # two disagree about which rows are out-of-sample, or that one report is
        # stale relative to the matrix on disk.
        pooled_base = ceiling.get("base_rate")
        configs = [r for r in (models.get("ranked") or [])
                   if r.get("config") == "fam_hgb_0"]
        if configs and pooled_base:
            got = configs[0]["oos_base_rate"]
            # The two modules compute this from the same out-of-sample rows and
            # currently agree BIT-IDENTICALLY (rel diff 0.0), so the tolerance can
            # be tight. The previous 5e-3 was 12x looser than the separation it
            # had to detect: the dense and stride-5 grids differ by 4.02e-4
            # relative (0.040894451 vs 0.040878010), so a ceiling report
            # regenerated on the stride-5 matrix while the search stayed dense
            # passed. The comment claimed the tolerance allowed for different row
            # filters, but a tolerance that cannot separate the two grids is not
            # allowing for anything. 1e-6 admits float noise and rejects a grid
            # change by more than two orders of magnitude.
            rel = abs(pooled_base - got) / max(pooled_base, 1e-12)
            f.check(rel < 1e-6,
                    f"base rate agrees across modules: ceiling "
                    f"{pooled_base:.9f} vs walkforward {got:.9f} "
                    f"(rel {rel:.3e}, grid separation is 4.02e-04)")

    # ------------------------------------------------------------------
    # Published CSVs, which nothing checked until now.
    #
    # The audit read only JSON, so every CSV in reports/ was unverified -- and
    # the two hit-rate files count signals differently in a way that is easy to
    # get wrong: README documents that the tradeability file's larger count is
    # the raw count plus the censored windows, while `unfillable` is a different,
    # smaller subset. That is exactly the kind of claim that should be executable
    # rather than prose.
    # ------------------------------------------------------------------
    def _spearman(xs: list, ys: list) -> float | None:
        """Spearman rank correlation, recomputed so a published rho is verified.

        Implemented here rather than importing scipy: the audit must run with
        only the standard library plus pandas/numpy, and this is a few lines.
        """
        pairs = [(x, y) for x, y in zip(xs, ys)
                 if x is not None and y is not None]
        if len(pairs) < 3:
            return None

        def rank(vals: list[float]) -> list[float]:
            order = sorted(range(len(vals)), key=lambda i: vals[i])
            ranks = [0.0] * len(vals)
            i = 0
            while i < len(order):
                j = i
                while j + 1 < len(order) and vals[order[j + 1]] == vals[order[i]]:
                    j += 1
                avg = (i + j) / 2.0 + 1.0
                for k in range(i, j + 1):
                    ranks[order[k]] = avg
                i = j + 1
            return ranks

        a = rank([float(p[0]) for p in pairs])
        b = rank([float(p[1]) for p in pairs])
        n = len(a)
        ma, mb = sum(a) / n, sum(b) / n
        num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
        da = sum((x - ma) ** 2 for x in a) ** 0.5
        db = sum((y - mb) ** 2 for y in b) ** 0.5
        if da == 0 or db == 0:
            return None
        return num / (da * db)

    hit = {r["strategy_id"]: r for r in load_csv("hitrate_vs_expectancy.csv")}
    trade = {r["label"]: r for r in load_csv("tradeability_by_strategy.csv")}
    raw = {r["strategy_id"]: r for r in load_csv("webpro_hit_rates.csv")}
    if hit and trade and raw:
        shared = sorted(set(hit) & set(trade))
        f.check(len(shared) > 0,
                f"hit-rate and tradeability CSVs share strategies ({len(shared)})")
        # identical sets of strategies, and the documented arithmetic relation
        f.check(set(hit) <= set(raw),
                "every strategy in hitrate_vs_expectancy.csv has a row in "
                "webpro_hit_rates.csv")
        bad_relation = []
        for sid in shared:
            expected = (int(raw[sid]["signals_raw__webpro"])
                        + int(raw[sid]["censored_signals__webpro"]))
            if int(trade[sid]["signals"]) != expected:
                bad_relation.append(sid)
        f.check(not bad_relation,
                f"tradeability signals == raw + censored for every shared strategy "
                f"({len(bad_relation)} violate: {bad_relation[:4]})")
        # `unfillable` must be a subset of the counted signals, and never equal
        # the raw/censored difference (the two are different quantities and the
        # prose says so).
        over = [s for s in shared
                if int(trade[s]["unfillable"]) > int(trade[s]["signals"])]
        f.check(not over, f"unfillable never exceeds signals ({over[:4]})")
        mism = [s for s in shared
                if int(hit[s]["signals"]) != int(raw[s]["signals_raw__webpro"])]
        f.check(not mism,
                f"hitrate_vs_expectancy signals == raw webpro signals "
                f"({len(mism)} differ: {mism[:4]})")
        # A hit rate must be a proportion of its own denominator.
        bad_rate = []
        for sid, row in hit.items():
            try:
                n, rate = int(row["signals"]), float(row["hit_rate"])
            except (TypeError, ValueError):
                continue
            if n and not (0.0 <= rate <= 1.0):
                bad_rate.append(sid)
        f.check(not bad_rate,
                f"hit rates lie in [0,1] ({bad_rate[:4]})")

    if f.verbose:
        print("  (checked the published CSV denominators)")

    # ------------------------------------------------------------------
    # live_readiness.json -- the report that answers "can this be traded at
    # all?", and previously no check read it.
    # ------------------------------------------------------------------
    lr = load("live_readiness.json")
    if lr:
        rows = lr.get("expectancy") or []
        f.check(bool(rows), f"live_readiness carries expectancy rows ({len(rows)})")
        for row in rows:
            label = row.get("label", "?")
            cost = row.get("cost_bps_round_trip")
            gross, net = row.get("gross_mean_return"), row.get("net_mean_return")
            if cost is not None and gross is not None and net is not None:
                # Net must be gross less the stated round-trip cost. This is the
                # report's central arithmetic claim and nothing verified it.
                expected = gross - float(cost) / 10_000.0
                f.check(
                    abs(net - expected) < 1e-9,
                    f"live_readiness '{label}': net {net:.6f} == gross {gross:.6f} "
                    f"- {cost}bp ({expected:.6f})",
                )
            sig, res = row.get("signals"), row.get("resolved")
            if sig is not None and res is not None:
                f.check(
                    int(res) <= int(sig),
                    f"live_readiness '{label}': resolved {res} <= signals {sig}",
                )
            a, b = row.get("net_p10"), row.get("net_p90")
            if a is not None and b is not None:
                f.check(a <= b,
                        f"live_readiness '{label}': net_p10 {a:.4f} <= net_p90 {b:.4f}")
        intrad = lr.get("intraday") or {}
        f.check(bool(intrad), "live_readiness carries the intraday assessment")

    # ------------------------------------------------------------------
    # lowzone_hit_rates.csv and webpro_scan_summary.json.
    #
    # The low-zone table is the V0x family's published hit-rate ledger, and its
    # "in_sample" flag is what stops an in-sample fit from being read as a live
    # result -- so an out-of-sample row whose precision exceeds its own Wilson
    # upper bound, or a lift that disagrees with precision / baseline, means the
    # table no longer says what the documents claim it says.
    # ------------------------------------------------------------------
    lz = load_csv("lowzone_hit_rates.csv")
    if lz:
        f.check(True, f"lowzone_hit_rates.csv parses ({len(lz)} rows)")
        bad_lift, bad_ci, bad_frac = [], [], []
        for row in lz:
            rid = f"{row.get('version')}/{row.get('regime')}"
            try:
                prec = float(row["bull_precision"])
                base = float(row["baseline_rate"])
                lift = float(row["lift_vs_baseline"])
                lo, hi = float(row["wilson_low"]), float(row["wilson_high"])
            except (KeyError, TypeError, ValueError):
                continue
            if base > 0 and abs(lift - prec / base) > 1e-3:
                bad_lift.append((rid, lift, prec / base))
            if not (0.0 <= lo <= prec <= hi <= 1.0):
                bad_ci.append((rid, lo, prec, hi))
            if not (0.0 <= prec <= 1.0):
                bad_frac.append(rid)
        f.check(not bad_lift,
                f"lowzone lift == precision / baseline ({len(bad_lift)} differ: "
                f"{bad_lift[:3]})")
        f.check(not bad_ci,
                f"lowzone Wilson bound brackets the precision ({len(bad_ci)} "
                f"violate: {bad_ci[:3]})")
        f.check(not bad_frac, f"lowzone precisions are proportions ({bad_frac[:3]})")

    scan = load("webpro_scan_summary.json")
    if scan:
        # The scan's own signal count must equal the headline figure the hit-rate
        # table reports for the same population; they are produced by the same
        # pass and drifted apart once already.
        emitted = scan.get("signals_emitted")
        f.check(isinstance(emitted, int) and emitted > 0,
                f"webpro_scan_summary reports signals_emitted ({emitted})")
        if raw:
            # Exact identity: the per-strategy raw counts plus the censored
            # windows account for EVERY emitted signal. The previous `total <=
            # emitted` left 9,219 rows of slack (the censored total), so nearly
            # 1.4% of the scan could vanish from the published table unnoticed.
            total = sum(int(r["signals_raw__webpro"]) for r in raw.values())
            censored = sum(int(r["censored_signals__webpro"]) for r in raw.values())
            f.check(
                total + censored == emitted,
                f"per-strategy raw {total:,} + censored {censored:,} == scan "
                f"total {emitted:,}",
            )
        f.check(scan.get("stride") is not None,
                "webpro_scan_summary records its stride")

    # ------------------------------------------------------------------
    # hitrate_vs_expectancy.json -- the source of the "hit rate ranks the
    # strategies backwards" claim (Spearman -0.511, 15 of 35 profitable) that
    # README quotes. The counts must match the CSV of the same name, or one of
    # the two is stale.
    # ------------------------------------------------------------------
    hve = load("hitrate_vs_expectancy.json")
    if hve:
        strategies = hve.get("strategies")
        # Require the field to be PRESENT before checking its value. The previous
        # form accepted None (`in (None, pos)`), so renaming or dropping a field
        # turned the check into a pass -- the same shape as the holdout-split
        # guard that read train_rows instead of n_train_rows and silently did
        # nothing.
        f.check(strategies is not None,
                "hitrate_vs_expectancy.json declares its strategy count")
        if strategies is not None and hit:
            f.check(strategies == len(hit),
                    f"hitrate_vs_expectancy.json strategies {strategies} matches "
                    f"the CSV row count ({len(hit)})")
        for key in ("positive_expectancy_count", "positive_at_target_count"):
            v = hve.get(key)
            f.check(v is not None,
                    f"hitrate_vs_expectancy.json declares {key}")
            if v is not None and strategies:
                f.check(0 <= int(v) <= int(strategies),
                        f"hitrate_vs_expectancy.json {key} {v} is within "
                        f"0..{strategies}")
        rho = hve.get("spearman_hit_rate_vs_net_expectancy")
        f.check(rho is not None,
                "hitrate_vs_expectancy.json declares its Spearman correlation")
        if rho is not None:
            f.check(-1.0 <= float(rho) <= 1.0,
                    f"hitrate_vs_expectancy.json Spearman rho {rho:.4f} is a "
                    f"correlation")
            # README quotes this value, so require it to match the recomputed
            # correlation from the CSV rather than merely being in range. A rho
            # that decayed from -0.511 to -0.20 would previously pass.
            if hit:
                recomputed = _spearman(
                    [_num(r.get("hit_rate")) for r in hit.values()],
                    [_num(r.get("net_expectancy")) for r in hit.values()],
                )
                if recomputed is not None:
                    f.check(
                        abs(float(rho) - recomputed) < 2e-3,
                        f"hitrate_vs_expectancy.json Spearman rho {float(rho):.4f} "
                        f"matches the correlation recomputed from the CSV "
                        f"({recomputed:.4f})",
                    )
        # Recompute the two counts from the CSV. If the JSON disagrees, the
        # document's headline claim no longer describes the published table.
        if hit:
            pos = sum(1 for r in hit.values()
                      if _num(r.get("net_expectancy")) is not None
                      and _num(r["net_expectancy"]) > 0)
            pos_t = sum(1 for r in hit.values()
                        if _num(r.get("net_expectancy_at_target")) is not None
                        and _num(r["net_expectancy_at_target"]) > 0)
            f.check(
                hve.get("positive_expectancy_count") == pos,
                f"hitrate_vs_expectancy.json positive_expectancy_count "
                f"{hve.get('positive_expectancy_count')} matches the CSV ({pos})",
            )
            f.check(
                hve.get("positive_at_target_count") == pos_t,
                f"hitrate_vs_expectancy.json positive_at_target_count "
                f"{hve.get('positive_at_target_count')} matches the CSV ({pos_t})",
            )

    # ------------------------------------------------------------------
    # tradeability.json -- the fillability ledger behind "15.8% of the best
    # strategy's signals cannot be bought" (README 9.2). Its columns are
    # arithmetically related, so they are all checkable with no external input.
    # ------------------------------------------------------------------
    tb = load("tradeability.json")
    if tb:
        def _check_tb(entry: dict, where: str) -> None:
            sig = entry.get("signals")
            if not sig:
                return
            hits, unf = entry.get("hits"), entry.get("unfillable")
            trade = entry.get("tradeable_signals")
            if trade is not None:
                f.check(
                    int(trade) == int(sig) - int(unf or 0),
                    f"tradeability {where}: tradeable_signals {trade} == "
                    f"signals {sig} - unfillable {unf}",
                )
            if hits is not None and entry.get("hit_rate") is not None:
                f.check(
                    abs(entry["hit_rate"] - hits / sig) < 1e-9,
                    f"tradeability {where}: hit_rate == hits / signals",
                )
            if unf is not None and entry.get("unfillable_pct") is not None:
                f.check(
                    abs(entry["unfillable_pct"] - unf / sig) < 1e-9,
                    f"tradeability {where}: unfillable_pct == unfillable / signals",
                )
            # The components must sum to the total, or a signal is double-counted
            # or lost between the reason columns.
            parts = [entry.get("one_word_limit"), entry.get("gapped_at_limit"),
                     entry.get("no_next_bar")]
            if unf is not None and all(p is not None for p in parts):
                f.check(
                    sum(int(p) for p in parts) >= int(unf),
                    f"tradeability {where}: reasons {parts} cover the "
                    f"{unf:,} unfillable signals",
                )
            th = entry.get("tradeable_hits")
            if th is not None and trade:
                f.check(
                    int(th) <= int(trade),
                    f"tradeability {where}: tradeable_hits {th} <= tradeable_signals {trade}",
                )

        _check_tb(tb.get("overall") or {}, "overall")
        for i, entry in enumerate(tb.get("worst_by_unfillable") or []):
            _check_tb(entry, f"worst[{i}]/{entry.get('label', '?')}")
        # `worst` is a top-10 by unfillable_pct, so it must be sorted desc.
        pcts = [e.get("unfillable_pct") for e in (tb.get("worst_by_unfillable") or [])
                if e.get("unfillable_pct") is not None]
        f.check(pcts == sorted(pcts, reverse=True),
                f"tradeability worst_by_unfillable is ordered by unfillable_pct "
                f"({len(pcts)} rows)")

    # ------------------------------------------------------------------
    # The two remaining artifacts, each a CSV twin of data checked above.
    # ------------------------------------------------------------------
    lrc = load_csv("live_readiness.csv")
    if lrc and lr:
        f.check(
            len(lrc) == len(lr.get("expectancy") or []),
            f"live_readiness.csv has one row per JSON expectancy entry "
            f"({len(lrc)} vs {len(lr.get('expectancy') or [])})",
        )
        # Spot-check that the CSV and JSON carry the same numbers, so a
        # regeneration of one without the other is caught.
        jrows = {r.get("label"): r for r in (lr.get("expectancy") or [])}
        mismatch = []
        for row in lrc:
            j = jrows.get(row.get("label"))
            if not j:
                mismatch.append((row.get("label"), "missing from JSON"))
                continue
            for col in ("signals", "resolved"):
                if row.get(col) and j.get(col) is not None:
                    if int(row[col]) != int(j[col]):
                        mismatch.append((row.get("label"), col))
        f.check(not mismatch,
                f"live_readiness.csv agrees with live_readiness.json "
                f"({len(mismatch)} differ: {mismatch[:3]})")

    cards = load_csv("webpro_cards_100_reproduction.csv")
    if cards:
        f.check(True, f"webpro_cards_100_reproduction.csv parses ({len(cards)} rows)")
        bad = []
        for row in cards:
            pred, tp, fp = (_num(row.get("yes_predictions")), _num(row.get("tp")),
                            _num(row.get("fp")))
            prec = _num(row.get("yes_precision"))
            if None in (pred, tp, fp, prec):
                continue
            # tp + fp must be the number of positive predictions, and precision
            # must be tp over that; a reproduction table that fails this cannot
            # be reproducing anything.
            if int(tp) + int(fp) != int(pred):
                bad.append((row.get("strategy_id"), "tp+fp != yes_predictions"))
            elif tp + fp > 0 and abs(prec - tp / (tp + fp)) > 1e-9:
                bad.append((row.get("strategy_id"), "precision != tp/(tp+fp)"))
        f.check(not bad,
                f"webpro_cards_100_reproduction arithmetic holds "
                f"({len(bad)} violate: {bad[:3]})")

    # ------------------------------------------------------------------
    # The precision frontier, which is the evidence for the central claim that
    # 70% is not reachable. It was 2 MB of published CSV that no check read.
    #
    # Each row is one realisable operating point: publish n_published rows and
    # get `precision`, at the cost of `fpr` and covering `recall`. Precision must
    # be a proportion, the rate must equal n / rows, and -- the property the
    # whole argument rests on -- publishing more rows can never raise precision
    # above the best smaller operating point by much, because the points come
    # from a prefix of one fixed ranking. Non-monotone movement is possible in
    # principle, so this asserts bounds rather than strict monotonicity.
    # ------------------------------------------------------------------
    for fname in ("ml_precision_frontier_oos.csv",
                  "ml_precision_frontier_insample.csv"):
        rows = load_csv(fname)
        if not rows:
            continue
        f.check(True, f"{fname} parses ({len(rows)} operating points)")
        bad_p, bad_rate, bad_fpr = [], [], []
        by_fold: dict[str, int] = {}
        # publish_rate is n_published / n_rows, so n_published / publish_rate
        # must recover the SAME row count for every point in a fold. This is a
        # strong, self-contained consistency check on the frontier: it needs no
        # external constant, and it catches a publish_rate that was computed
        # against the wrong denominator or a row count from another grid.
        implied_rows: dict[str, list[float]] = {}
        for row in rows:
            fold = row.get("fold", "?")
            by_fold[fold] = by_fold.get(fold, 0) + 1
            try:
                p = float(row["precision"])
                fpr = float(row["fpr"])
                recall = float(row["recall"])
                pub = float(row["n_published"])
                rate = float(row["publish_rate"])
            except (KeyError, TypeError, ValueError):
                continue
            if not (0.0 <= p <= 1.0) or not (0.0 <= fpr <= 1.0) or not (0.0 <= recall <= 1.0):
                bad_p.append((fold, row.get("n_published")))
            if not (0.0 <= rate <= 1.0):
                bad_rate.append((fold, row.get("n_published")))
            if pub > 0 and rate > 0:
                implied_rows.setdefault(fold, []).append(pub / rate)
            # publish_rate is the share of ALL rows published, so it is a
            # weighted average of recall (share of positives) and fpr (share of
            # negatives): rate = (recall*P + fpr*N) / (P + N). It must therefore
            # lie between them. An earlier version of this check asserted
            # recall + fpr <= 1, which is wrong -- the two have different
            # denominators, and publishing everything gives 1 + 1.
            lo, hi = min(recall, fpr), max(recall, fpr)
            if not (lo - 1e-9 <= rate <= hi + 1e-9):
                bad_fpr.append((fold, row.get("n_published"), recall, fpr, rate))
        f.check(not bad_p, f"{fname}: precision/fpr/recall are proportions "
                           f"({len(bad_p)} violate: {bad_p[:3]})")
        f.check(not bad_rate, f"{fname}: publish_rate is a proportion "
                              f"({len(bad_rate)} violate: {bad_rate[:3]})")
        f.check(not bad_fpr, f"{fname}: publish_rate lies between recall and fpr "
                             f"({len(bad_fpr)} violate: {bad_fpr[:3]})")
        f.check(len(by_fold) >= 1,
                f"{fname}: fold column populated across {len(by_fold)} fold(s)")
        for fold, count in sorted(by_fold.items()):
            f.check(count > 1, f"{fname}: fold {fold} has {count} points")
            implied = implied_rows.get(fold) or []
            if len(implied) > 1:
                spread = max(implied) - min(implied)
                f.check(
                    spread < 1.0,
                    f"{fname}: fold {fold} implies one row count "
                    f"({implied[0]:,.0f}, spread {spread:.2f} across "
                    f"{len(implied)} points)",
                )


    # Every report that carries a base rate must agree on which grid it came
    # from. Mixing grids silently is the failure mode that produced the stale
    # 15.98% in an earlier revision of the documents.
    #
    # Compare the MEDIAN base rate over configs that completed every fold and saw
    # a non-trivial number of signals. An earlier version compared each report's
    # top-level `oos_base_rate` field, which raised a false alarm: a report's
    # most precise config can be a degenerate one that completed only 2 of 4
    # folds, so its base rate describes those two folds rather than the grid.
    full_fold_bases: dict[str, float] = {}
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        rows = [r for r in (report.get("ranked") or [])
                if r.get("n_folds", 0) >= 4 and r.get("oos_signals", 0) >= 100
                and r.get("oos_base_rate")]
        if rows:
            full_fold_bases[name] = float(
                statistics.median([r["oos_base_rate"] for r in rows])
            )
    if len(full_fold_bases) > 1:
        vals = list(full_fold_bases.values())
        spread = max(vals) - min(vals)
        # The tolerance has to be tighter than the difference it is meant to
        # detect. On one matrix the same label and fold count give a base rate
        # that is bit-identical across configurations, so the only reason two
        # full-fold rows differ is that they came from different matrices -- and
        # the two grids in play differ by 1.644e-05 (0.040894451 dense vs
        # 0.040878010 stride-5). The previous 5e-4 tolerance was 30x too loose
        # and would have accepted a report mixing the two.
        f.check(spread < 1e-8,
                f"search reports share one grid: median base rate over full-fold "
                f"configs spans {spread:.3e} "
                f"({ {k: round(v, 11) for k, v in full_fold_bases.items()} })")

    # A single report must not MIX grids. The check above compares reports to
    # each other via a median, which is blind to one report containing rows from
    # two grids: ml_search_wide.json carried 21 rows at 0.0264875 (label_close)
    # and 29 at 0.04087801 (label_high on the stride-5 matrix) at the same time,
    # and the median simply picked one. Rows with the same label and the same
    # completed-fold count on one matrix must share a base rate exactly; a
    # spread within such a group means the report was assembled from different
    # runs or different matrices.
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        groups: dict[tuple, set[float]] = {}
        for r in (report.get("ranked") or []):
            base = r.get("oos_base_rate")
            if not base or r.get("n_folds", 0) < 4 or r.get("oos_signals", 0) < 100:
                continue
            groups.setdefault((r.get("label"), r.get("n_folds")), set()).add(
                round(float(base), 8)
            )
        for (label, n_folds), bases in sorted(groups.items(), key=str):
            f.check(
                len(bases) == 1,
                f"{name}: rows with label={label} and {n_folds} completed folds "
                f"share one base rate (found {sorted(bases)})",
            )

    # ------------------------------------------------------------------
    # Baseline provenance.
    #
    # `reports/webpro_baselines.json` and `reports/lowzone_baselines.json` both
    # publish a field called `bull_rate` for the same three regimes and they
    # disagree (webpro 3.0348% vs 3.0893%, low504 4.6956% vs 4.2099%), because
    # `scan_all` counts the scanned grid (min_history plus stride) while
    # `backtest_lowzone` counts every resolved bar.
    #
    # This looked like a defect and was reported as one -- "low504 z=+11.50, not
    # noise". It is not: that z treats 2.68M dependent panel rows as independent
    # draws. With market dates as clusters the same contrast is z=+1.24,
    # bootstrap p=0.22. The gap is a legitimate population difference (the
    # `_seq >= 60` warm-up filter is also a calendar filter), and no published
    # lift is wrong, because each family already divides by its OWN baseline.
    #
    # So the invariant to enforce is not that the two agree -- it is that each
    # says which population it measured, and that the ML reports' third
    # population is not confused with either. Without this, a future reader
    # repeats exactly the analysis above and reaches the wrong conclusion.
    # ------------------------------------------------------------------
    for name, expect_id in (("webpro_baselines.json", "scanned"),
                            ("lowzone_baselines.json", "panel")):
        report = load(name)
        if not report:
            continue
        for regime, entry in report.items():
            if not isinstance(entry, dict) or "bull_rate" not in entry:
                continue
            pop = entry.get("population")
            if pop is None:
                # The reports predate the provenance fields; regeneration is
                # pending. Skipping silently would hide that the guard is not yet
                # doing anything, so the gap is counted and named.
                f.note(f"{name}:{regime} carries no `population` block yet, so its "
                       f"base rate is not labelled as the {expect_id!r} population; "
                       f"regenerate to arm this check")
                continue
            pid = pop.get("population_id") if isinstance(pop, dict) else pop
            f.check(
                pid == expect_id,
                f"{name}:{regime} labels its base rate as the {expect_id!r} "
                f"population (found {pid!r})",
            )
            rows = entry.get("candidates") or entry.get("evaluated_points")
            if isinstance(pop, dict) and pop.get("rows") and rows:
                f.check(
                    int(pop["rows"]) == int(rows),
                    f"{name}:{regime} population rows {pop['rows']:,} matches "
                    f"the published denominator {int(rows):,}",
                )

    # The ML reports measure a THIRD population (walk-forward folds on the
    # feature matrix), and quoting its base rate beside either file above is a
    # category error. Flag the value if it appears unresolved in prose.
    ml_base = (load("ml_precision_ceiling.json") or {}).get("base_rate")
    if ml_base:
        for doc in ("README.md", "TARGET_70PCT.md"):
            path = ROOT / doc
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            if f"{ml_base*100:.4f}" in text or f"{ml_base*100:.2f}" in text:
                f.check(
                    bool(re.search(r"(walk-forward|fold|ML|feature matrix)", text)),
                    f"{doc} quotes the ML base rate {ml_base*100:.4f}% and says "
                    f"which population it belongs to",
                )

    # Every matrix the reports could have come from, keyed by stride. Checking
    # only `s5` was a dead guard: the holdout module writes
    # `n_train_rows`/`n_holdout_rows` but this check read
    # `train_rows`/`holdout_rows`, so both `.get()` calls returned None, the
    # `if` was False, and the check NEVER RAN while still being counted as a
    # pass. A holdout report that had silently regressed to a different grid
    # went undetected for exactly this reason.
    matrices: dict[int, dict] = {}
    for path in sorted((ROOT / "outputs" / "ml").glob("matrix_*_meta.json")):
        try:
            meta = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            f.check(False, f"{path.name} parses: {exc}")
            continue
        meta["_name"] = path.name
        f.check(meta.get("features") == 82,
                f"{path.name} advertises 82 features (found {meta.get('features')})")
        if meta.get("stride") is not None:
            matrices[int(meta["stride"])] = meta

    f.check(bool(matrices), "at least one feature matrix is present on disk")

    holdout = load("ml_final_holdout.json")
    if holdout:
        train_n = holdout.get("n_train_rows")
        hold_n = holdout.get("n_holdout_rows")
        # Missing keys are now a FAILURE, not a silent pass. This is the whole
        # point: a renamed field must break the check loudly.
        f.check(
            train_n is not None and hold_n is not None,
            f"holdout report carries n_train_rows/n_holdout_rows "
            f"(found {train_n!r}/{hold_n!r})",
        )
        stride = holdout.get("stride")
        f.check(stride is not None, "holdout report records the stride it used")
        if train_n is not None and hold_n is not None and stride is not None:
            # Match the holdout against the matrix for ITS OWN stride. Comparing
            # it against every matrix on disk is wrong: the stride-1 holdout
            # legitimately does not fit the stride-5 matrix, and those are both
            # valid artifacts serving different purposes.
            meta = matrices.get(int(stride))
            f.check(
                meta is not None,
                f"a matrix exists for the holdout's stride {stride} "
                f"(found strides {sorted(matrices)})",
            )
            if meta is not None:
                f.check(
                    train_n + hold_n <= meta["rows"],
                    f"holdout split {train_n:,}+{hold_n:,} fits within "
                    f"{meta['_name']} ({meta['rows']:,} rows, stride {stride})",
                )


# ---------------------------------------------------------------------------
# 4. Prose drift: numbers in Markdown vs the reports they cite
# ---------------------------------------------------------------------------
def extract_table_cells(text: str) -> list[str]:
    cells: list[str] = []
    for line in text.splitlines():
        if line.count("|") >= 2:
            cells.extend(c.strip() for c in line.split("|") if c.strip())
    return cells


# Markers that a line is narrating a correction rather than asserting a current
# value. Deliberately matched against the LINE ONLY: an earlier version searched
# a 7-line window, so a word like "previous" in a neighbouring table row exempted
# the headline result two lines below it.
CORRECTION_MARKERS = re.compile(
    r"(correct|retired|supersed|was reported|no longer|previously|"
    r"revision|history|changed|old stride|earlier version)",
    re.I,
)


def _is_correction_prose(line: str) -> bool:
    """True if this line explains a past value rather than asserting a live one."""
    return bool(CORRECTION_MARKERS.search(line))


def check_prose(f: Findings, verbose: bool) -> None:
    print("\n[4] prose drift against reports")

    holdout = load("ml_final_holdout.json")
    # Only the holdout is needed for the holdout-prose checks. Requiring the
    # ceiling file as well meant an unrelated missing report silently disabled
    # them -- and made the explicit `f.check(False, ...)` guard below
    # unreachable, so the intended loud failure never fired. A missing report is
    # now reported by load() itself, and the checks that CAN run do run.
    if not holdout:
        f.check(False, "ml_final_holdout.json is available for the prose checks")
        return

    # ------------------------------------------------------------------
    # Every report that a grid could shift must say which grid it used.
    #
    # Two grids are in circulation and they give different base rates
    # (0.04089445 dense vs 0.04087801 stride-5), so a report without a `stride`
    # field cannot be compared with anything. Skipping a report because it
    # happens to predate the stamping is how the gap stayed invisible, so the
    # reports that genuinely lack the field are named individually with the grid
    # they were measured on, established from their own payload.
    # ------------------------------------------------------------------
    known_grid = {
        # n_rows 281,227 and oos_base_rate 0.04087801 = the stride-5 matrix.
        "ml_crosssec_final.json": ("stride-5", "n_rows=281,227, base=0.04087801"),
        "ml_crosssec_hgb0.json": ("stride-5", "same run as ml_crosssec_final"),
        # These three were regenerated on the dense grid but by a run whose code
        # predated the provenance stamp, so the numbers are right and the grid is
        # provable from the payload while the `stride` field is absent. They are
        # listed and then scheduled for regeneration, not exempted permanently.
        "ml_search_models.json": ("stride-1", "median full-fold base=0.04089445"),
        "ml_search_ablation.json": ("stride-1", "median full-fold base=0.04089445"),
        "ml_null_tests.json": ("stride-1", "n_rows=2,680,715 = the dense matrix"),
    }
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json", "ml_crosssec_final.json",
                 "ml_crosssec_hgb0.json", "ml_precision_ceiling.json",
                 "ml_null_tests.json", "ml_concentration.json"):
        report = load(name)
        if not report:
            continue
        stride = report.get("stride")
        if stride is None and name in known_grid:
            grid, why = known_grid[name]
            f.note(f"{name} has no `stride` field but is {grid} ({why}); "
                   f"regenerate to stamp it")
            continue
        f.check(stride is not None,
                f"{name} records the stride it was measured on")

    #
    # The previous version only grepped for literal strings ("13.61" in the
    # document). That is blind in the one direction that counts: prose asserting
    # 13.61% passed while reports/ml_final_holdout.json said 11.05%, because the
    # check never compared the two. A published report silently regressed to a
    # different grid and 107 checks still reported "0 problems".
    #
    # So: derive the expected strings FROM THE REPORT and require the documents
    # to agree. If the report changes, the documents must change with it or this
    # fails.
    # ------------------------------------------------------------------
    if holdout:
        pct = holdout["precision"] * 100
        lift = holdout["lift"]
        # Accept either one or two decimal places in prose.
        precision_variants = {f"{pct:.1f}", f"{pct:.2f}"}
        lift_variants = {f"{lift:.1f}", f"{lift:.2f}"}
        signals_variants = {f"{holdout['signals']:,}", str(holdout["signals"])}
        for doc in ("README.md", "TARGET_70PCT.md"):
            path = ROOT / doc
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            # The holdout precision must appear somewhere in each headline doc.
            f.check(
                any(v in text for v in precision_variants),
                f"{doc} states the holdout precision {pct:.2f}% "
                f"(report says {holdout['precision']:.6f})",
            )
            f.check(
                any(v in text for v in lift_variants),
                f"{doc} states the holdout lift {lift:.2f}x "
                f"(report says {holdout['lift']:.6f})",
            )
            # And must NOT still assert a superseded holdout precision, unless
            # the line is recording that history. Correction blocks are how this
            # document legitimately explains the 12.14% -> 11.05% -> 13.61%
            # chain, so blockquotes and fenced code are exempt; a bare claim in
            # body text is not.
            stale = {12.14, 11.05, 13.61} - {round(pct, 2)}
            in_fence = False
            for line_no, line in enumerate(text.splitlines(), 1):
                stripped = line.lstrip()
                if stripped.startswith("```"):
                    in_fence = not in_fence
                    continue
                if in_fence or stripped.startswith(">"):
                    continue
                # Exempt only the line itself, or a line that is plainly
                # narrating the correction. The previous version searched a
                # 7-line window for words like "previous", which silently
                # exempted README's headline results row because the row above it
                # says "HGB (previous baseline)". That masked exactly the line
                # this check exists to protect. Blockquotes and fenced code are
                # already exempt above, so correction prose keeps its escape.
                if _is_correction_prose(line):
                    continue
                for value in stale:
                    if re.search(rf"\b{value:.2f}\s*%", line):
                        f.check(
                            False,
                            f"{doc}:{line_no} asserts holdout precision "
                            f"{value:.2f}%, superseded; report says {pct:.2f}%",
                        )

    if verbose:
        print(f"  (checked headline figures against the payload)")

    # ------------------------------------------------------------------
    # Tie the headline tables to their reports.
    #
    # Grepping a document for a literal ("13.61") only proves the document
    # contains that string; it cannot prove the string is still TRUE. These
    # checks parse the table rows and require each configuration's numbers to
    # exist in the report the prose says they came from. When ml_search_wide.json
    # is regenerated on a different grid, its cited table must be updated with it
    # or this fails.
    # ------------------------------------------------------------------
    def table_rows(doc: str, header_needle: str) -> list[list[str]]:
        """Data rows of the first Markdown table under a header line."""
        path = ROOT / doc
        if not path.exists():
            return []
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            if header_needle not in line:
                continue
            rows: list[list[str]] = []
            for follow in lines[i + 1:]:
                if follow.strip().startswith("|"):
                    cells = [c.strip() for c in follow.strip().strip("|").split("|")]
                    if cells and not set("".join(cells)) <= set("-: "):
                        rows.append(cells)
                elif rows:
                    break
            if rows:
                return rows
        return []

    def pct(cell: str) -> float | None:
        m = re.search(r"([0-9]+(?:\.[0-9]+)?)\s*%", cell)
        return float(m.group(1)) if m else None

    def count(cell: str) -> int | None:
        m = re.search(r"([0-9][0-9,]*)\s*$", cell.replace("**", "").strip())
        return int(m.group(1).replace(",", "")) if m else None

    wide = load("ml_search_wide.json")
    if wide:
        ranked = wide.get("ranked") or []
        by_sig = {r.get("oos_signals"): r for r in ranked}
        # Column layout: Configuration | In-sample | Out-of-sample | Signals | Folds
        for cells in table_rows("TARGET_70PCT.md", "showing **both** numbers"):
            if len(cells) < 4:
                continue
            ins, oos, sig = pct(cells[1]), pct(cells[2]), count(cells[3])
            if oos is None or sig is None:
                continue
            row = by_sig.get(sig)
            if row is None:
                f.check(False,
                        f"TARGET_70PCT.md §4 cites {sig:,} signals, which is in no "
                        f"ml_search_wide.json row")
                continue
            f.check(
                abs(row["oos_precision"] * 100 - oos) < 0.005,
                f"TARGET_70PCT.md §4 says {sig:,} signals score {oos:.2f}% OOS; "
                f"the report says {row['oos_precision']*100:.2f}%",
            )
            if ins is not None:
                f.check(
                    abs(row["insample_precision"] * 100 - ins) < 0.005,
                    f"TARGET_70PCT.md §4 says {sig:,} signals were {ins:.2f}% "
                    f"in-sample; the report says "
                    f"{row['insample_precision']*100:.2f}%",
                )

    models = load("ml_search_models.json")
    if models:
        by_name = {r["config"]: r for r in (models.get("ranked") or [])}
        # README's table mixes the four fitted families with rows sourced from
        # other reports (the per-fold oracle, the top-1-per-session experiment,
        # the one-shot holdout). Only the family rows belong to this report, so
        # scope the check to rows that actually name a family.
        family_words = ("Random Forest", "HGB", "ExtraTrees", "Logistic",
                        "Gradient Boosting")
        for cells in table_rows("README.md", "| Configuration | In-sample |"):
            if len(cells) < 4:
                continue
            if not any(w.lower() in cells[0].lower() for w in family_words):
                continue
            ins, oos, sig = pct(cells[1]), pct(cells[2]), count(cells[3])
            if None in (ins, oos, sig):
                continue
            match = [r for r in by_name.values()
                     if r.get("oos_signals") == sig
                     and abs(r["oos_precision"] * 100 - oos) < 0.005]
            f.check(bool(match),
                    f"README.md family row '{cells[0]}' ({ins}% in / {oos}% OOS "
                    f"/ {sig:,} signals) exists in ml_search_models.json")

    # The 2026-holdout treatment table. It sat on a superseded run (8,352 signals
    # at 12.07%) because the counts it quoted were printed to stdout and never
    # stored. Now that the report carries {precision, signals} per treatment, the
    # table can be verified cell by cell.
    conc = load("ml_concentration.json")
    if conc and (conc.get("holdout") or {}).get("drop_top_dates"):
        ho = conc["holdout"]
        wanted = {"As published": 0, "Drop busiest date": 1,
                  "Drop 3 busiest dates": 3, "Drop 5 busiest dates": 5,
                  "Drop 10 busiest dates": 10}
        drops = {int(k): v for k, v in ho["drop_top_dates"].items()
                 if isinstance(v, dict)}
        for cells in table_rows("TARGET_70PCT.md", "**2026 holdout, same treatment"):
            if len(cells) < 3:
                continue
            label = cells[0]
            got_p, got_n = pct(cells[1]), count(cells[2])
            n_drop = wanted.get(label)
            if n_drop is None or n_drop not in drops or got_p is None:
                # Half-sample rows are checked against the halves below.
                if label.startswith("First half") and got_p is not None:
                    f.check(
                        abs(ho["first_half_precision"] * 100 - got_p) < 0.005,
                        f"TARGET_70PCT.md says first half {got_p:.2f}%; report "
                        f"says {ho['first_half_precision']*100:.2f}%")
                elif label.startswith("Second half") and got_p is not None:
                    f.check(
                        abs(ho["second_half_precision"] * 100 - got_p) < 0.005,
                        f"TARGET_70PCT.md says second half {got_p:.2f}%; report "
                        f"says {ho['second_half_precision']*100:.2f}%")
                continue
            row = drops[n_drop]
            f.check(
                abs(row["precision"] * 100 - got_p) < 0.005,
                f"TARGET_70PCT.md says '{label}' is {got_p:.2f}%; the report "
                f"says {row['precision']*100:.2f}%",
            )
            if got_n is not None:
                f.check(
                    row["signals"] == got_n,
                    f"TARGET_70PCT.md says '{label}' leaves {got_n:,} signals; "
                    f"the report says {row['signals']:,}",
                )

    if verbose:
        print("  (tied headline tables to their source reports)")

    # A document must not assert a specific audit-check count. The count changes
    # whenever a check is added, so any such claim is stale by construction --
    # README said "still 111 checks, 0 problems" while the audit ran 368 with
    # 2 problems. Stating the current count would only move the problem, so the
    # pattern is rejected outright.
    for doc in ("README.md", "TARGET_70PCT.md", "RESULTS.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        for line_no, line in enumerate(
            path.read_text(encoding="utf-8").splitlines(), 1
        ):
            m = re.search(r"\b(\d+)\s+checks\b", line)
            if m and not _is_correction_prose(line):
                f.check(False,
                        f"{doc}:{line_no} asserts '{m.group(1)} checks', a moving "
                        f"number; describe what is checked instead")

    # Retired figures, kept with the reason so the list doubles as a record of
    # corrections rather than a mystery. Only values that are retired in EVERY
    # context belong here; a value that is still current somewhere (15.98% is
    # the live walk-forward baseline) must not, or the check cries wolf and gets
    # switched off.
    retired = {
        "20.23": "precision ceiling before the frontier grid was densified",
        "3.87": "lift computed against an unweighted-mean base rate",
        "3.58": "lift computed against a signal-weighted base rate",
        "24.54": "frontier computed on the stride-5 grid",
    }
    prose_docs = ["README.md", "TARGET_70PCT.md", "RESULTS.md"]
    for doc in prose_docs:
        path = ROOT / doc
        if not path.exists():
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        in_fence = False
        for line_no, line in enumerate(lines, 1):
            stripped = line.lstrip()
            if stripped.startswith("```"):
                in_fence = not in_fence
                continue
            # Blockquotes and fenced code are where the documents explain their
            # own corrections; body text asserting a retired number is a find.
            # Line-scoped, not window-scoped: see CORRECTION_MARKERS.
            if in_fence or stripped.startswith(">") or _is_correction_prose(line):
                continue
            for value, why in retired.items():
                if re.search(rf"\b{re.escape(value)}\s*(x|×)", line):
                    f.check(False, f"{doc}:{line_no} asserts lift {value}x, "
                                   f"retired because {why}")
            if re.search(r"ceiling[^|]*\b20\.23\b", line, re.I):
                f.check(False, f"{doc}:{line_no} asserts a 20.23 ceiling, "
                               f"retired because {why}")

    if verbose:
        print(f"  (scanned {len(prose_docs)} documents for retired figures)")


# ---------------------------------------------------------------------------
# 4b. The frontier numbers: ceiling and recall-floor tables
# ---------------------------------------------------------------------------
def _frontier_rows(name: str) -> list[dict]:
    """Read a precision-frontier CSV from reports/."""
    path = REPORTS / name
    if not path.exists():
        LOAD_ERRORS.append(f"reports/{name} is referenced by the audit but missing")
        return []
    with path.open(encoding="utf-8", newline="") as fh:
        return list(_csv.DictReader(fh))


def check_frontier(f: Findings) -> None:
    """Verify the numbers TARGET_70PCT.md calls its ceiling.

    These are the document's central claim -- how good the best achievable
    precision is -- and until now nothing compared them to any artifact. The
    payload exists in ml_precision_ceiling.json and the frontier CSVs.
    """
    print("\n[4b] precision ceiling and recall-floor tables")

    ceiling = load("ml_precision_ceiling.json")
    text = (ROOT / "TARGET_70PCT.md").read_text(encoding="utf-8") \
        if (ROOT / "TARGET_70PCT.md").exists() else ""

    if ceiling:
        by_min = ceiling.get("practical_ceiling_by_min_signals") or {}
        # The published floor table: minimum signals -> max precision, pooled and
        # rank-normalised.
        pairs = []
        for floor in ("250", "1000", "2000", "5000", "10000"):
            row = by_min.get(floor)
            if row:
                pairs.append((int(floor),
                              row.get("max_precision_raw"),
                              row.get("max_precision_rank")))
        for floor, raw, rank in pairs:
            if raw is None:
                continue
            raw_pct, rank_pct = raw * 100, (rank or 0) * 100
            # The document prints these to two decimals in its floor table.
            needle = f"| {floor:,} | {raw_pct:.2f}%"
            f.check(needle in text,
                    f"TARGET_70PCT.md floor table states {floor:,} -> "
                    f"{raw_pct:.2f}% (report says {raw:.6f})")
            if rank is not None:
                f.check(f"{rank_pct:.2f}%" in text,
                        f"TARGET_70PCT.md states the rank-normalised ceiling "
                        f"{rank_pct:.2f}% for {floor:,} signals")

        # THE headline ceiling. README and TARGET both lead with it.
        top = ceiling.get("practical_ceiling_250plus_raw")
        top_rank = ceiling.get("practical_ceiling_250plus_rank")
        if top is not None:
            val = f"{top * 100:.2f}"
            for doc in ("TARGET_70PCT.md", "README.md"):
                p = ROOT / doc
                if p.exists():
                    f.check(val in p.read_text(encoding="utf-8"),
                            f"{doc} states the headline ceiling {val}% "
                            f"(report says {top!r})")
        if top_rank is not None:
            f.check(f"{top_rank * 100:.2f}" in text,
                    f"TARGET_70PCT.md states the rank ceiling "
                    f"{top_rank * 100:.2f}% (report says {top_rank!r})")

        # The absolute maximum is what makes 70% unreachable, so it must be
        # consistent with the floor table's own maximum.
        absolute = ceiling.get("absolute_max_precision_oos")
        if absolute is not None and top is not None:
            f.check(abs(absolute - top) < 5e-4,
                    f"ml_precision_ceiling absolute max {absolute:.6f} agrees "
                    f"with the >=250-signal ceiling {top:.6f}")

    # The recall-floor table lives in the document but is computed from the OOS
    # frontier: for each recall floor, the single global row with the highest
    # precision among those meeting the floor, pooled. Established by
    # scripts/scratch/_probe_recall_floor.py, which reproduces all six published
    # pairs exactly; a per-fold variant does not, so the rule is asserted here
    # rather than assumed.
    #
    # This parses the DOCUMENT's rows and compares them to the frontier. An
    # earlier version compared the frontier against hard-coded constants, which
    # verified the CSV but could not notice the document changing -- the check
    # would have passed with the table deleted.
    oos = _frontier_rows("ml_precision_frontier_oos.csv")
    if oos and text:
        floors = [(0.50, "50%"), (0.30, "30%"), (0.20, "20%"),
                  (0.10, "10%"), (0.05, "5%"), (0.02, "2%")]
        # Locate the recall-floor table: data rows are `| <floor> | <pct> | <n> |`.
        doc_rows: list[tuple[str, float, int]] = []
        for line in text.splitlines():
            if line.count("|") < 3:
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 3:
                continue
            m = re.match(r"^[≥>=]*\s*(\d+)%$", cells[0])
            p = re.match(r"^([\d.]+)%$", cells[1])
            n = re.match(r"^([\d,]+)$", cells[2])
            if m and p and n:
                doc_rows.append((m.group(1), float(p.group(1)),
                                 int(n.group(1).replace(",", ""))))
        f.check(len(doc_rows) >= 4,
                f"TARGET_70PCT.md recall-floor table parses "
                f"({len(doc_rows)} data rows found)")
        seen = set()
        expect = (("50", 11.46, 43989), ("30", 13.42, 23834),
                  ("20", 14.15, 15436), ("10", 16.64, 7493),
                  ("5", 19.42, 3831), ("2", 28.57, 735))
        for label, want_pct, want_n in expect:
            row = next((r for r in doc_rows if r[0] == label), None)
            if row is None:
                continue
            seen.add(label)
            _label, got_pct, got_n = row
            # Independently recompute the frontier value for this floor.
            floor_frac = int(label) / 100.0
            cand = [r for r in oos if float(r["recall"]) >= floor_frac]
            best = max(cand, key=lambda r: float(r["precision"])) if cand else None
            if best is None:
                f.check(False,
                        f"TARGET_70PCT.md states a recall-floor >= {label}% row "
                        f"but the frontier has no row meeting it")
                continue
            exp_pct = float(best["precision"]) * 100
            exp_n = int(best["n_published"])
            f.check(
                abs(got_pct - exp_pct) < 0.02 and abs(got_n - exp_n) < 2,
                f"TARGET_70PCT.md recall-floor >= {label}% row is "
                f"{got_pct:.2f}% / {got_n:,}; the frontier gives "
                f"{exp_pct:.2f}% / {exp_n:,}",
            )
        missing = {"50", "30", "20", "10", "5", "2"} - seen
        if missing:
            f.check(False,
                    f"TARGET_70PCT.md recall-floor table is missing rows for "
                    f"{sorted(missing)}")


    # ------------------------------------------------------------------
    # RESULTS.md -- the adversarial review's largest coverage gap.
    #
    # It is generated by src.render_results from webpro_hit_rates.csv, but no
    # check compared the two: none of bull_precision_deduped, lift__webpro or
    # baseline__webpro appeared anywhere in this file, so all 35 rows of its main
    # table, its three base-rate rows and its headline leader_momentum row were
    # free to drift. Its numbers are read here straight back out of the document
    # and matched against the CSV that produced them.
    # ------------------------------------------------------------------
    results_md = ROOT / "RESULTS.md"
    web = load_csv("webpro_hit_rates.csv")
    if results_md.exists() and web:
        by_id = {r["strategy_id"]: r for r in web}
        rmd = results_md.read_text(encoding="utf-8")
        # The main table: | # | `strategy` | signals | hits | **rate** | base | lift | ...
        doc_rows = {}
        for line in rmd.splitlines():
            if line.count("|") < 9:
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            m = re.match(r"^`([a-z0-9_]+)`$", cells[1]) if len(cells) > 2 else None
            if not m:
                continue
            sid = m.group(1)
            if sid in by_id and sid not in doc_rows:
                doc_rows[sid] = cells
        f.check(len(doc_rows) >= 30,
                f"RESULTS.md main table parses ({len(doc_rows)} strategy rows)")
        # Every published strategy must appear; a silently dropped row is a
        # silently dropped result.
        absent = sorted(set(by_id) - set(doc_rows))
        f.check(not absent,
                f"RESULTS.md lists every strategy in webpro_hit_rates.csv "
                f"({len(absent)} missing: {absent[:4]})")
        bad = []
        for sid, cells in doc_rows.items():
            r = by_id[sid]
            want_sig = int(r["signals_deduped__webpro"])
            want_hits = int(r["bull_hits_deduped__webpro"])
            want_rate = float(r["bull_precision_deduped__webpro"]) * 100
            # Columns: 0 '#', 1 strategy, 2 signals, 3 hits, 4 '**rate**'.
            # The rate cell carries BOTH markdown bold markers and a percent
            # sign; stripping only '*' leaves '%', float() raises, and an earlier
            # version of this loop then skipped the WHOLE row -- so the signal and
            # hit comparisons below never ran and the check passed vacuously on
            # all 35 rows. Strip both, and treat each field independently.
            got = [_num(re.sub(r"[*%]", "", c)) for c in cells[2:5]]
            if got[0] is not None and int(got[0]) != want_sig:
                bad.append((sid, "signals", got[0], want_sig))
            if got[1] is not None and int(got[1]) != want_hits:
                bad.append((sid, "hits", got[1], want_hits))
            if got[2] is not None and abs(got[2] - want_rate) > 0.005:
                bad.append((sid, "hit rate", got[2], round(want_rate, 2)))
        f.check(not bad,
                f"RESULTS.md row values match webpro_hit_rates.csv "
                f"({len(bad)} differ: {bad[:3]})")
        # Guard against the vacuous pass: if the value columns did not parse, the
        # comparison above checks nothing while reporting success.
        parsed_rows = sum(
            1 for cells in doc_rows.values()
            if _num(re.sub(r"[*%]", "", cells[2])) is not None
        )
        f.check(parsed_rows >= 30,
                f"RESULTS.md row values are parseable ({parsed_rows} of "
                f"{len(doc_rows)} rows yielded a signal count)")

        # The three base-rate rows, which every lift in the file divides by.
        base_doc = {}
        for line in rmd.splitlines():
            if line.count("|") < 5:
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            m = re.match(r"^`(webpro|low60|low504)`$", cells[0]) if cells else None
            if m and len(cells) >= 5:
                pts = _num(cells[2].replace(",", ""))
                bull = _num(cells[3].rstrip("%"))
                if pts is not None and bull is not None:
                    base_doc[m.group(1)] = (int(pts), bull)
        f.check(len(base_doc) == 3,
                f"RESULTS.md base-rate table parses ({sorted(base_doc)})")
        if "webpro" in base_doc:
            _pts, bull = base_doc["webpro"]
            # The scanned grid's natural bull rate, which the document also prints
            # inline as the divisor for every lift.
            live = float(web[0]["baseline__webpro"]) * 100
            f.check(abs(bull - live) < 5e-4,
                    f"RESULTS.md base-rate table webpro bull rate {bull:.4f}% "
                    f"matches the CSV ({live:.4f}%)")
            f.check(f"{live:.3f}%" in rmd,
                    f"RESULTS.md quotes the scanned base rate {live:.3f}% inline")

        # The headline row, called out in prose elsewhere in the repo.
        if "leader_momentum" in by_id:
            r = by_id["leader_momentum"]
            pct = float(r["bull_precision_deduped__webpro"]) * 100
            lift = float(r["lift__webpro"])
            f.check(f"**{pct:.2f}%**" in rmd,
                    f"RESULTS.md states the leader_momentum hit rate "
                    f"**{pct:.2f}%**")
            f.check(f"{lift:.2f}x" in rmd,
                    f"RESULTS.md states the leader_momentum lift {lift:.2f}x")


# ---------------------------------------------------------------------------
# 5. Markdown structure
# ---------------------------------------------------------------------------
def check_markdown_structure(f: Findings) -> None:
    print("\n[5] markdown structure")
    for doc in ("README.md", "TARGET_70PCT.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()

        numbers = []
        for line in lines:
            m = re.match(r"^## (\d+)\.", line)
            if m:
                numbers.append((int(m.group(1)), line.strip()))
        expected = list(range(1, len(numbers) + 1))
        got = [n for n, _ in numbers]
        f.check(got == expected,
                f"{doc}: sections numbered 1..{len(numbers)} with no gaps or "
                f"duplicates (found {got})")

        # Every "section N" / "§N" reference must resolve.
        valid = set(got)
        dangling = []
        for line_no, line in enumerate(lines, 1):
            for m in re.finditer(r"§(\d+)", line):
                ref = int(m.group(1))
                if ref not in valid:
                    dangling.append(f"line {line_no} -> §{ref}")
        f.check(not dangling,
                f"{doc}: all §-references resolve"
                f"{'' if not dangling else ' (' + '; '.join(dangling[:4]) + ')'}")

    # Relative Markdown links must point at files that exist.
    link_re = re.compile(r"\[[^\]]+\]\(([^)#][^)]*)\)")
    for doc in ("README.md", "TARGET_70PCT.md", "RESULTS.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        missing = []
        for target in link_re.findall(path.read_text(encoding="utf-8")):
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            if not (ROOT / target.split("#")[0]).exists():
                missing.append(target)
        f.check(not missing,
                f"{doc}: relative links resolve"
                f"{'' if not missing else ' (missing: ' + str(missing[:4]) + ')'}")


# ---------------------------------------------------------------------------
# 6. Reported commit must match the tree
# ---------------------------------------------------------------------------
def check_no_orphan_reports(f: Findings) -> None:
    print("\n[6] report inventory")
    on_disk = {p.name for p in REPORTS.glob("*.json")}
    csvs = {p.name for p in REPORTS.glob("*.csv")}
    print(f"  ({len(on_disk)} JSON reports, {len(csvs)} CSVs present)")
    # `load` records its own failures into LOAD_ERRORS; count them so this check
    # can actually fail. Previously it called f.check(True, ...) unconditionally,
    # so "15 reports parse" was printed even when every one was malformed.
    before = len(LOAD_ERRORS)
    for name in sorted(on_disk):
        load(name)
    failed = len(LOAD_ERRORS) - before
    f.check(failed == 0,
            f"{len(on_disk) - failed} of {len(on_disk)} JSON reports parse")

    # Which published artifacts does this audit actually read? A report that no
    # check names is published and unverified, which is how nine of them --
    # including live_readiness.json, which carries the intraday answer -- sat
    # outside every check while the audit reported no problems.
    #
    # Coverage is derived from actual load()/load_csv() CALL SITES, not from
    # filename strings anywhere in the source. The previous version regexed the
    # whole file, so a filename mentioned only in a comment or in the known_grid
    # table counted as covered -- ml_crosssec_final.json was reported as read
    # while no value in it was ever compared.
    src = Path(__file__).read_text(encoding="utf-8")
    referenced = set(re.findall(
        r"(?:load|load_csv)\(\s*[\"']([A-Za-z0-9_]+\.(?:json|csv))[\"']", src
    ))
    unreferenced = sorted((on_disk | csvs) - referenced)
    for name in unreferenced:
        f.note(f"reports/{name} is published but no check reads it")
    print(f"  ({len(unreferenced)} published artifact(s) outside every check)")
    if f.verbose:
        print(f"  (checked artifacts: {len(referenced)})")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verbose", action="store_true",
                    help="print every check, not only failures")
    args = ap.parse_args()

    print(f"auditing reports in {REPORTS}")
    f = Findings(verbose=args.verbose)
    check_arithmetic(f)
    check_pooling(f)
    check_cross_report(f)
    check_prose(f, args.verbose)
    check_frontier(f)
    check_markdown_structure(f)
    check_no_orphan_reports(f)

    # Fold in anything load()/load_csv() could not read. These are recorded, not
    # printed-and-forgotten, so an unreadable report fails the run instead of
    # quietly removing the checks that depend on it.
    for msg in dict.fromkeys(LOAD_ERRORS):
        f.check(False, msg)

    print("\n" + "=" * 70)
    print(f"{f.checked} checks run, {len(f.problems)} problem(s)")
    for p in f.problems:
        print(f"  - {p}")
    if f.notes:
        print(f"\n{len(f.notes)} known gap(s), reported but not failures:")
        for n in f.notes:
            print(f"  - {n}")
    return 1 if f.problems else 0


if __name__ == "__main__":
    sys.exit(main())
