"""Audit the published reports and documents for internal consistency.

This repository publishes numbers in three places that can drift apart:

* ``reports/*.json`` — machine-readable ground truth, regenerated by the ``src``
  and ``src.ml`` modules;
* the Markdown documents (``README.md``, ``TARGET_70PCT.md``, ``RESULTS.md``);
* the audit documents under ``audit/``.

Nothing previously checked that a figure quoted in prose still matched the report
it came from. That gap has already produced two real defects in this project: a
precision ceiling quoted as 20.23% after the grid was densified, and a lift
quoted as 3.87x then "corrected" to 3.58x when the exact pooled value is 3.91x.
Both were found by hand, late. This module finds that class of error
mechanically.

Checks performed
----------------
1. Arithmetic inside each report: lift equals precision divided by base rate,
   signal and hit counts are consistent, intervals bracket their point estimate.
2. Pooling consistency: where a report carries per-fold detail AND a pooled
   figure, the pooled figure must equal the ratio-of-sums recomputation.
3. Cross-report agreement: quantities computed by more than one module (base
   rates, row counts) must agree exactly.
4. Prose drift: numbers asserted in Markdown tables are compared against the
   report they name.
5. Structural hygiene: Markdown section numbering is sequential, and every
   internal "section N" reference resolves to a section that exists.

Usage
-----
    python scripts/audit_reports.py            # report problems, exit 1 if any
    python scripts/audit_reports.py --verbose  # print every check performed
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"

# Tolerance for float comparisons. Reports round to ~4 significant figures in
# prose, so a relative tolerance of 1e-6 is tight enough to catch a genuine
# mismatch while ignoring JSON float round-tripping.
RTOL = 1e-6


class Findings:
    def __init__(self, verbose: bool = False) -> None:
        self.problems: list[str] = []
        self.checked = 0
        self.verbose = verbose

    def check(self, ok: bool, message: str) -> bool:
        self.checked += 1
        if ok:
            if self.verbose:
                print(f"  ok    {message}")
        else:
            self.problems.append(message)
            print(f"  FAIL  {message}")
        return ok

    def close(self, a: float, b: float, *, rtol: float = RTOL) -> bool:
        if a is None or b is None:
            return False
        scale = max(abs(a), abs(b), 1e-12)
        return abs(a - b) / scale <= rtol


def load(name: str) -> dict | None:
    path = REPORTS / name
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"  FAIL  {name} is not valid JSON: {exc}")
        return None


# ---------------------------------------------------------------------------
# 1. Arithmetic inside a report
# ---------------------------------------------------------------------------
def check_arithmetic(f: Findings) -> None:
    print("\n[1] arithmetic inside each report")

    holdout = load("ml_final_holdout.json")
    if holdout:
        p, base, lift = (holdout.get("precision"), holdout.get("base_rate"),
                         holdout.get("lift"))
        f.check(f.close(p / base, lift),
                f"ml_final_holdout: lift {lift:.4f} == precision/base "
                f"{p / base:.4f}")
        sig, hits = holdout.get("signals"), holdout.get("hits")
        f.check(f.close(hits / sig, p),
                f"ml_final_holdout: hits/signals {hits / sig:.6f} == "
                f"precision {p:.6f}")
        lo, hi = holdout.get("date_clustered_95", [None, None])
        f.check(lo < p < hi,
                f"ml_final_holdout: date-clustered CI [{lo:.4f},{hi:.4f}] "
                f"brackets precision {p:.4f}")
        wlo, whi = holdout.get("wilson_95", [None, None])
        f.check(wlo < p < whi,
                f"ml_final_holdout: Wilson CI [{wlo:.4f},{whi:.4f}] "
                f"brackets precision {p:.4f}")

    ceiling = load("ml_precision_ceiling.json")
    if ceiling:
        rows, pos, base = (ceiling.get("oos_rows"), ceiling.get("oos_positives"),
                           ceiling.get("base_rate"))
        f.check(f.close(pos / rows, base),
                f"ml_precision_ceiling: {pos}/{rows} == base {base:.6f}")

    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        ranked = report.get("ranked") or []
        bad = [
            r["config"] for r in ranked
            if r.get("oos_base_rate") and r.get("oos_precision") is not None
            and not f.close(r["oos_precision"] / r["oos_base_rate"],
                            r.get("oos_lift", 0.0), rtol=1e-5)
        ]
        f.check(not bad,
                f"{name}: every row's lift == precision/base "
                f"({len(ranked)} rows{'' if not bad else ', bad: ' + str(bad[:3])})")


# ---------------------------------------------------------------------------
# 2. Pooled figures must equal the ratio-of-sums
# ---------------------------------------------------------------------------
def check_pooling(f: Findings) -> None:
    print("\n[2] pooled figures vs per-fold recomputation")
    for name in ("ml_search_models.json", "ml_search_wide.json",
                 "ml_search_ablation.json"):
        report = load(name)
        if not report:
            continue
        for r in report.get("ranked") or []:
            sig = r.get("per_fold_signals")
            pre = r.get("per_fold_oos")
            if not sig or not pre:
                continue
            total = sum(sig)
            if total == 0:
                continue
            recomputed = sum(p * n for p, n in zip(pre, sig)) / total
            if not f.check(f.close(recomputed, r["oos_precision"], rtol=1e-9),
                           f"{name}/{r['config']}: pooled precision "
                           f"{r['oos_precision']:.6f} == signal-weighted "
                           f"recomputation {recomputed:.6f}"):
                break


# ---------------------------------------------------------------------------
# 3. Quantities computed by more than one module must agree
# ---------------------------------------------------------------------------
def check_cross_report(f: Findings) -> None:
    print("\n[3] cross-report agreement")

    ceiling = load("ml_precision_ceiling.json")
    models = load("ml_search_models.json")
    if ceiling and models:
        # The ceiling module reports the pooled out-of-sample base rate
        # independently of the walk-forward module. They share fold definitions,
        # so they must agree exactly; a mismatch means the two disagree about
        # which rows are out-of-sample.
        pooled_base = ceiling.get("base_rate")
        configs = [r for r in (models.get("ranked") or [])
                   if r.get("config") == "fam_hgb_0"]
        if configs:
            f.check(f.close(pooled_base, configs[0]["oos_base_rate"], rtol=1e-4),
                    f"base rate agrees across modules: ceiling {pooled_base:.6f} "
                    f"vs walkforward {configs[0]['oos_base_rate']:.6f}")

    matrix_meta = ROOT / "outputs" / "ml" / "matrix_h10_t30_s5_meta.json"
    if matrix_meta.exists():
        meta = json.loads(matrix_meta.read_text(encoding="utf-8"))
        holdout = load("ml_final_holdout.json")
        if holdout:
            train_n = holdout.get("train_rows")
            hold_n = holdout.get("holdout_rows")
            if train_n and hold_n:
                f.check(train_n + hold_n <= meta["rows"],
                        f"holdout split {train_n}+{hold_n} fits within matrix "
                        f"{meta['rows']} rows")
        f.check(meta.get("features") == 82,
                f"matrix advertises 82 features (found {meta.get('features')})")


# ---------------------------------------------------------------------------
# 4. Prose drift: numbers in Markdown vs the reports they cite
# ---------------------------------------------------------------------------
def extract_table_cells(text: str) -> list[str]:
    cells: list[str] = []
    for line in text.splitlines():
        if line.count("|") >= 2:
            cells.extend(c.strip() for c in line.split("|") if c.strip())
    return cells


def check_prose(f: Findings, verbose: bool) -> None:
    print("\n[4] prose drift against reports")

    holdout = load("ml_final_holdout.json")
    ceiling = load("ml_precision_ceiling.json")
    if not (holdout and ceiling):
        print("  (skipped: reports missing)")
        return

    # Figures that MUST appear in the headline documents, and figures that must
    # NOT appear because they were corrected.
    must_appear = {
        "README.md": ["12.14", "4.17", "15.98", "23.81"],
        "TARGET_70PCT.md": ["12.14", "24.54", "15.98"],
    }
    for doc, needles in must_appear.items():
        path = ROOT / doc
        if not path.exists():
            f.check(False, f"{doc} exists")
            continue
        text = path.read_text(encoding="utf-8")
        for needle in needles:
            f.check(needle in text,
                    f"{doc} cites {needle}")

    # Retired figures. Each is kept here with the reason so the list doubles as
    # a record of corrections rather than a mystery.
    retired = {
        "20.23": "precision ceiling before the frontier grid was densified",
        "3.87": "lift computed against an unweighted-mean base rate",
        "3.58": "lift computed against a signal-weighted base rate",
    }
    # A correction table legitimately lists retired values next to the reasons
    # they were retired. Rather than matching keywords on the line, mark the
    # block: any line inside a fenced "correction" region, or within a table
    # whose header names the retired value as superseded, is exempt. This keeps
    # the check useful (it still catches a live claim) without forcing the
    # document to hide the history.
    exempt_markers = re.compile(
        r"(correct|retired|earlier|previous|was reported|not the|superseded|"
        r"original|first \"?fix)",
        re.I,
    )
    prose_docs = ["README.md", "TARGET_70PCT.md", "RESULTS.md"]
    for doc in prose_docs:
        path = ROOT / doc
        if not path.exists():
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        # Look back a few lines for an exemption marker, which covers a
        # correction table whose caption sits above it.
        for line_no, line in enumerate(lines, 1):
            window = "\n".join(lines[max(0, line_no - 7):line_no])
            if exempt_markers.search(line) or exempt_markers.search(window):
                continue
            for value, why in retired.items():
                if re.search(rf"\b{re.escape(value)}\s*(x|×)", line):
                    f.check(False, f"{doc}:{line_no} asserts lift {value}x, "
                                   f"retired because {why}")
            if re.search(r"ceiling[^|]*\b20\.23\b", line, re.I):
                f.check(False, f"{doc}:{line_no} asserts a 20.23 ceiling, "
                               f"retired because {why}")

    if verbose:
        print(f"  (scanned {len(prose_docs)} documents for retired figures)")


# ---------------------------------------------------------------------------
# 5. Markdown structure
# ---------------------------------------------------------------------------
def check_markdown_structure(f: Findings) -> None:
    print("\n[5] markdown structure")
    for doc in ("README.md", "TARGET_70PCT.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()

        numbers = []
        for line in lines:
            m = re.match(r"^## (\d+)\.", line)
            if m:
                numbers.append((int(m.group(1)), line.strip()))
        expected = list(range(1, len(numbers) + 1))
        got = [n for n, _ in numbers]
        f.check(got == expected,
                f"{doc}: sections numbered 1..{len(numbers)} with no gaps or "
                f"duplicates (found {got})")

        # Every "section N" / "§N" reference must resolve.
        valid = set(got)
        dangling = []
        for line_no, line in enumerate(lines, 1):
            for m in re.finditer(r"§(\d+)", line):
                ref = int(m.group(1))
                if ref not in valid:
                    dangling.append(f"line {line_no} -> §{ref}")
        f.check(not dangling,
                f"{doc}: all §-references resolve"
                f"{'' if not dangling else ' (' + '; '.join(dangling[:4]) + ')'}")

    # Relative Markdown links must point at files that exist.
    link_re = re.compile(r"\[[^\]]+\]\(([^)#][^)]*)\)")
    for doc in ("README.md", "TARGET_70PCT.md", "RESULTS.md"):
        path = ROOT / doc
        if not path.exists():
            continue
        missing = []
        for target in link_re.findall(path.read_text(encoding="utf-8")):
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            if not (ROOT / target.split("#")[0]).exists():
                missing.append(target)
        f.check(not missing,
                f"{doc}: relative links resolve"
                f"{'' if not missing else ' (missing: ' + str(missing[:4]) + ')'}")


# ---------------------------------------------------------------------------
# 6. Reported commit must match the tree
# ---------------------------------------------------------------------------
def check_no_orphan_reports(f: Findings) -> None:
    print("\n[6] report inventory")
    on_disk = {p.name for p in REPORTS.glob("*.json")}
    print(f"  ({len(on_disk)} JSON reports present)")
    for name in sorted(on_disk):
        load(name)  # surface JSON errors early
    f.check(True, f"{len(on_disk)} reports parse")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verbose", action="store_true",
                    help="print every check, not only failures")
    args = ap.parse_args()

    print(f"auditing reports in {REPORTS}")
    f = Findings(verbose=args.verbose)
    check_arithmetic(f)
    check_pooling(f)
    check_cross_report(f)
    check_prose(f, args.verbose)
    check_markdown_structure(f)
    check_no_orphan_reports(f)

    print("\n" + "=" * 70)
    print(f"{f.checked} checks run, {len(f.problems)} problem(s)")
    for p in f.problems:
        print(f"  - {p}")
    return 1 if f.problems else 0


if __name__ == "__main__":
    sys.exit(main())
