# Register the four-hourly report audit using schtasks.exe.
#
# Why schtasks and not Register-ScheduledTask: the latter requires elevation and
# fails with "Access is denied" (0x80070005) for a normal user. schtasks can
# register a per-user task without elevation, which is all this needs -- the job
# only reads the repo, writes a log, and runs git with cached credentials.
#
# Why XML and not `/sc HOURLY`: `schtasks /create /sc HOURLY` can set the interval
# and start time but NOT the power settings, and the first registration inherited
# `DisallowStartIfOnBatteries=true` on a laptop. That means the audit is skipped
# ENTIRELY and silently whenever the machine is unplugged -- no run, no log, no
# alert, and the published status simply goes stale. Registering from an XML
# definition is the only way to set those flags without elevation.
#
# Run:    powershell -ExecutionPolicy Bypass -File scripts\register_report_audit_task.ps1
# At a chosen time:
#         powershell -ExecutionPolicy Bypass -File scripts\register_report_audit_task.ps1 `
#             -StartAt '2026-09-18T23:15:00'
# Remove: schtasks /delete /tn "ProWeb60d-ReportAudit" /f

[CmdletBinding()]
param(
    [string]$TaskName = 'ProWeb60d-ReportAudit',
    [int]$EveryHours = 4,
    # Local time. Defaults to five minutes from now, the previous behaviour.
    [string]$StartAt = '',
    [switch]$RunNow
)

$ErrorActionPreference = 'Stop'

# schtasks writes its diagnostics to stderr even on success, and PowerShell
# turns native stderr into a terminating error when ErrorActionPreference is
# Stop. Wrap every schtasks call so only the real exit code decides success.
function Invoke-Schtasks {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Args)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $output = & schtasks @Args 2>&1 | ForEach-Object { "$_" }
        return [pscustomobject]@{ Code = $LASTEXITCODE; Output = ($output -join "`n") }
    } finally {
        $ErrorActionPreference = $prev
    }
}

$repo = Split-Path -Parent $PSScriptRoot
$script = Join-Path $repo 'scripts\scheduled_report_audit.py'
if (-not (Test-Path $script)) { throw "audit script not found: $script" }
$python = (Get-Command python -ErrorAction Stop).Source

New-Item -ItemType Directory -Force -Path (Join-Path $repo 'logs\report_audit') | Out-Null

# A wrapper .cmd keeps quoting predictable. It also guarantees the working
# directory and PYTHONPATH are right regardless of how the scheduler invokes it.
#
# The first version of this wrapper appended everything to a `logs/` file that
# `.gitignore` excludes, so the audit ran every four hours and published
# nothing. The scheduler now commits `reports/AUDIT_STATUS.md`, which is
# tracked, so the result is visible on GitHub. SCHEDULER_OUT keeps a local
# transcript for debugging; it is not the deliverable.
$wrapper = Join-Path $repo 'scripts\run_report_audit.cmd'
$wrapperBody = @"
@echo off
REM Generated by register_report_audit_task.ps1 -- do not edit by hand.
REM Publishes reports/AUDIT_STATUS.md to origin/main; see
REM scripts/scheduled_report_audit.py for what it does and why.
set PYTHONPATH=$repo
set GIT_TERMINAL_PROMPT=0
cd /d "$repo"
"$python" "$script" --quiet >> "$repo\logs\report_audit\scheduler.out" 2>&1
"@
Set-Content -Path $wrapper -Encoding ASCII -Value $wrapperBody

# Resolve the start boundary.
if ([string]::IsNullOrWhiteSpace($StartAt)) {
    $startBoundary = (Get-Date).AddMinutes(5)
} else {
    $startBoundary = [datetime]::Parse($StartAt)
}
if ($startBoundary -lt (Get-Date)) {
    Write-Warning "StartAt $($startBoundary.ToString('s')) is in the past; the task will run at the next repetition boundary or via -RunNow."
}
$sb = $startBoundary.ToString('yyyy-MM-ddTHH:mm:ss')

$userId = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value

# Power/catch-up settings, and why each matters on a laptop:
#   DisallowStartIfOnBatteries=false  - the previous value silently skipped every
#       run while unplugged. On a laptop that is most of the day.
#   StopIfGoingOnBatteries=false      - likewise, do not kill a run in progress.
#   StartWhenAvailable=true           - if the machine slept through the trigger,
#       run at the next opportunity instead of dropping the slot.
#   WakeToRun=false                   - do NOT wake the machine; this is a passive
#       audit and waking a laptop on a schedule is hostile.
$xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>$env:USERDOMAIN\$env:USERNAME</Author>
    <Description>Four-hourly consistency audit of reports/ in $repo. Publishes reports/AUDIT_STATUS.md.</Description>
    <URI>\$TaskName</URI>
  </RegistrationInfo>
  <Triggers>
    <TimeTrigger>
      <StartBoundary>$sb</StartBoundary>
      <Enabled>true</Enabled>
      <Repetition>
        <Interval>PT${EveryHours}H</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
    </TimeTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$userId</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT15M</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>$wrapper</Command>
    </Exec>
  </Actions>
</Task>
"@

$xmlPath = Join-Path $env:TEMP "proweb60d_task_$PID.xml"
# schtasks requires UTF-16 for an XML definition. `-Encoding Unicode` is UTF-16LE
# with BOM in PowerShell 5.1, which is what it expects.
Set-Content -Path $xmlPath -Encoding Unicode -Value $xml

Write-Host "repo    : $repo"
Write-Host "python  : $python"
Write-Host "wrapper : $wrapper"
Write-Host "start   : $sb (every $EveryHours h)"

# Remove any previous registration so this is idempotent. A missing task is the
# normal case on first run, so a non-zero exit here is expected and ignored.
$del = Invoke-Schtasks /delete /tn $TaskName /f
if ($del.Code -eq 0) { Write-Host "removed previous registration of '$TaskName'" }

$create = Invoke-Schtasks /create /tn $TaskName /xml $xmlPath /f
Write-Host $create.Output
Remove-Item $xmlPath -ErrorAction SilentlyContinue
if ($create.Code -ne 0) {
    throw "schtasks /create failed (exit $($create.Code)): $($create.Output)"
}

Write-Host ""
Write-Host "verifying registration..."
$q = Invoke-Schtasks /query /tn $TaskName /fo LIST /v
$q.Output -split "`n" |
    Where-Object { $_ -match 'TaskName|Next Run Time|Status|Schedule Type|Repeat: Every|Task To Run|Run As User' } |
    ForEach-Object { $_.Trim() }

if ($RunNow) {
    Write-Host ""
    Write-Host "starting the task now to verify it actually runs..."
    $r = Invoke-Schtasks /run /tn $TaskName
    Write-Host $r.Output
    Start-Sleep -Seconds 60
    Write-Host ""
    Write-Host "last result:"
    $q2 = Invoke-Schtasks /query /tn $TaskName /fo LIST /v
    $q2.Output -split "`n" |
        Where-Object { $_ -match 'Last Run Time|Last Result|Next Run Time' } |
        ForEach-Object { $_.Trim() }
    Write-Host ""
    Write-Host "most recent audit log:"
    Get-ChildItem (Join-Path $repo 'logs\report_audit') -Filter 'audit_*.log' -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1 |
        ForEach-Object { "  $($_.FullName)  ($($_.LastWriteTime))" }
}
