<#
.SYNOPSIS
Register the delayed fix-up task: one hour after each GPT-Pro web audit slot.

.DESCRIPTION
Division of labour this task encodes:
  - The expert/ML REVIEW is produced by GPT Pro in a browser. It writes
    docs/audits/expert-ml/*.md and commits them. Nothing here audits.
  - THIS task runs in DSH one hour later, reads whatever report the web review
    published, fixes the code it points at, and pushes.

Scheduled slots (expert/ML audit is JST 03/07/11/15/19/23 = Beijing 02/06/10/14/18/22;
+1 hour gives Beijing 03/07/11/15/19/23, i.e. :15 past with a 15-minute buffer).

WHY XML VIA schtasks AND NOT Register-ScheduledTask
`Register-ScheduledTask` requires elevation. `schtasks /create /xml` does not,
and it is the only non-elevated way to set the power flags. Registering with
`schtasks /sc HOURLY` normally inherits `DisallowStartIfOnBatteries=true`, which
would make this task silently skip every run on an unplugged laptop -- the same
trap the report-audit task hit. Hence the XML.

NOTE: schtasks writes to stderr even on success, so the wrapper below decides by
exit code only and never by the presence of stderr text.

.PARAMETER RunNow
Start one run immediately after registering, to prove the task really launches.

.PARAMETER EveryHours
Repetition interval in hours (default 4, matching the audit cadence).
#>
[CmdletBinding()]
param(
    [string]$TaskName = "ProWeb60d-Fixup",
    [double]$EveryHours = 4,
    [string]$StartAt = "03:15",
    [switch]$RunNow
)

$ErrorActionPreference = "Stop"

$Repo      = "D:\ccc\pro-web-60d-strategy"
$Python    = "C:\Users\30834\miniconda3\python.exe"
$Script    = Join-Path $Repo "scripts\run_fixup.py"
$CmdFile   = Join-Path $Repo "scripts\run_fixup.cmd"
$XmlFile   = Join-Path $Repo "scripts\run_fixup.task.xml"
$LogDir    = Join-Path $Repo "logs\fixup"

if (-not (Test-Path $Python)) { throw "python not found: $Python" }
if (-not (Test-Path $Script)) { throw "script not found: $Script" }
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

function Invoke-Schtasks {
    param([string[]]$Arguments)
    # schtasks writes progress to stderr even on SUCCESS. Under
    # $ErrorActionPreference='Stop' PowerShell 5.1 promotes any native stderr
    # write that is captured (2>&1) into a TERMINATING NativeCommandError, so a
    # succeeding create would abort the script and look like a failure. Measured:
    # that is exactly what happened on the first two registrations. Relax the
    # preference around the call and decide by exit code alone.
    $previous = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $output = & schtasks.exe @Arguments 2>&1
        $code = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $previous
    }
    if ($code -ne 0) {
        throw "schtasks $($Arguments -join ' ') failed (exit $code): $output"
    }
    return $output
}

# --- the .cmd wrapper -------------------------------------------------------
# The task runs cmd rather than python directly so the environment is explicit
# and the log survives a crash of the python process itself.
$cmdBody = @"
@echo off
REM Generated by register_fixup_task.ps1 -- do not edit by hand.
REM Reads the newest expert/ML report (written by the GPT-Pro web review) and
REM fixes the code it names; see scripts/run_fixup.py.
set PYTHONPATH=$Repo
set GIT_TERMINAL_PROMPT=0
cd /d "$Repo"
"$Python" "$Script" >> "$LogDir\scheduler.out" 2>&1
"@
# ASCII is deliberate: the body contains no non-ASCII characters, and a BOM or
# an ANSI codepage remap of the path would break cmd parsing.
Set-Content -Path $CmdFile -Value $cmdBody -Encoding ASCII
Write-Host "wrote $CmdFile"

# --- the task XML -----------------------------------------------------------
$interval = "PT$([int]$EveryHours)H"
# The agent may legitimately run for up to 90 minutes (run_fixup.py allows 5400s),
# so the limit must exceed that or Windows would kill a working run mid-push.
$timeLimit = "PT2H30M"
$startBoundary = (Get-Date -Format "yyyy-MM-dd") + "T$StartAt" + ":00"

$xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Delayed fix-up: one hour after each GPT-Pro expert/ML web audit, read the newest report in docs/audits/expert-ml, fix the code it names, verify, and push to origin/main.</Description>
    <URI>\$TaskName</URI>
  </RegistrationInfo>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-55458904-1253535992-457034622-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
    </Principal>
  </Principals>
  <Settings>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <ExecutionTimeLimit>$timeLimit</ExecutionTimeLimit>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <StartWhenAvailable>true</StartWhenAvailable>
    <WakeToRun>false</WakeToRun>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
  </Settings>
  <Triggers>
    <TimeTrigger>
      <StartBoundary>$startBoundary</StartBoundary>
      <Repetition>
        <Interval>$interval</Interval>
      </Repetition>
    </TimeTrigger>
  </Triggers>
  <Actions Context="Author">
    <Exec>
      <Command>$CmdFile</Command>
    </Exec>
  </Actions>
</Task>
"@
# The schtasks XML import requires UTF-16LE; a UTF-8 file is rejected outright.
Set-Content -Path $XmlFile -Value $xml -Encoding Unicode
Write-Host "wrote $XmlFile"

# --- register (idempotent) --------------------------------------------------
# Deleting a task that does not exist yet is an expected failure on a first
# install, so it is swallowed deliberately: treating it as fatal would make this
# script work only on re-registration, never on the first run.
$previous = $ErrorActionPreference
$ErrorActionPreference = "Continue"
try {
    & schtasks.exe /delete /tn $TaskName /f 2>&1 | Out-Null
} finally {
    $ErrorActionPreference = $previous
}
Invoke-Schtasks @("/create", "/tn", $TaskName, "/xml", $XmlFile, "/f") | Out-Null
Write-Host "registered task: $TaskName"

if ($RunNow) {
    Invoke-Schtasks @("/run", "/tn", $TaskName) | Out-Null
    Write-Host "started one run now (verification)"
}

Write-Host ""
& schtasks.exe /query /tn $TaskName /fo LIST /v 2>&1 |
    Select-String -Pattern 'TaskName|Status|Last Run Time|Last Result|Next Run Time|Task To Run|Scheduled Task State' |
    ForEach-Object { "  $($_.Line.Trim())" }
