# Register the four-hourly report audit using schtasks.exe.
#
# Why schtasks and not Register-ScheduledTask: the latter requires elevation and
# fails with "Access is denied" (0x80070005) for a normal user. schtasks can
# register a per-user task without elevation, which is all this needs — the job
# only reads the repo, writes a log, and runs git with cached credentials.
#
# Run:  powershell -ExecutionPolicy Bypass -File scripts\register_report_audit_task.ps1
# Remove: schtasks /delete /tn "ProWeb60d-ReportAudit" /f

[CmdletBinding()]
param(
    [string]$TaskName = 'ProWeb60d-ReportAudit',
    [int]$EveryHours = 4,
    [switch]$RunNow
)

$ErrorActionPreference = 'Stop'

# schtasks writes its diagnostics to stderr even on success, and PowerShell
# turns native stderr into a terminating error when ErrorActionPreference is
# Stop. Wrap every schtasks call so only the real exit code decides success.
function Invoke-Schtasks {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Args)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $output = & schtasks @Args 2>&1 | ForEach-Object { "$_" }
        return [pscustomobject]@{ Code = $LASTEXITCODE; Output = ($output -join "`n") }
    } finally {
        $ErrorActionPreference = $prev
    }
}

$repo = Split-Path -Parent $PSScriptRoot
$script = Join-Path $repo 'scripts\scheduled_report_audit.py'
if (-not (Test-Path $script)) { throw "audit script not found: $script" }
$python = (Get-Command python -ErrorAction Stop).Source

New-Item -ItemType Directory -Force -Path (Join-Path $repo 'logs\report_audit') | Out-Null

# A wrapper .cmd keeps quoting predictable. It also guarantees the working
# directory and PYTHONPATH are right regardless of how the scheduler invokes it.
$wrapper = Join-Path $repo 'scripts\run_report_audit.cmd'
$wrapperBody = @"
@echo off
REM Generated by register_report_audit_task.ps1 -- do not edit by hand.
set PYTHONPATH=$repo
cd /d "$repo"
"$python" "$script" --quiet >> "$repo\logs\report_audit\scheduler.out" 2>&1
"@
Set-Content -Path $wrapper -Encoding ASCII -Value $wrapperBody

Write-Host "repo    : $repo"
Write-Host "python  : $python"
Write-Host "wrapper : $wrapper"

# Remove any previous registration so this is idempotent. A missing task is the
# normal case on first run, so a non-zero exit here is expected and ignored.
$del = Invoke-Schtasks /delete /tn $TaskName /f
if ($del.Code -eq 0) { Write-Host "removed previous registration of '$TaskName'" }

# /sc HOURLY /mo 4 repeats indefinitely starting at the given time.
$startTime = (Get-Date).AddMinutes(5).ToString('HH:mm')
Write-Host "registering: $TaskName every $EveryHours hour(s) from $startTime"
$create = Invoke-Schtasks /create /tn $TaskName /tr "`"$wrapper`"" `
    /sc HOURLY /mo "$EveryHours" /st $startTime /f
Write-Host $create.Output
if ($create.Code -ne 0) {
    throw "schtasks /create failed (exit $($create.Code)): $($create.Output)"
}

Write-Host ""
Write-Host "verifying registration..."
$q = Invoke-Schtasks /query /tn $TaskName /fo LIST /v
$q.Output -split "`n" |
    Where-Object { $_ -match 'TaskName|Next Run Time|Status|Schedule Type|Repeat: Every|Task To Run' } |
    ForEach-Object { $_.Trim() }

if ($RunNow) {
    Write-Host ""
    Write-Host "starting the task now to verify it actually runs..."
    $r = Invoke-Schtasks /run /tn $TaskName
    Write-Host $r.Output
    Start-Sleep -Seconds 45
    Write-Host ""
    Write-Host "last result:"
    $q2 = Invoke-Schtasks /query /tn $TaskName /fo LIST /v
    $q2.Output -split "`n" |
        Where-Object { $_ -match 'Last Run Time|Last Result|Next Run Time' } |
        ForEach-Object { $_.Trim() }
    Write-Host ""
    Write-Host "most recent audit log:"
    Get-ChildItem (Join-Path $repo 'logs\report_audit') -Filter 'audit_*.log' -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1 |
        ForEach-Object { "  $($_.FullName)  ($($_.LastWriteTime))" }
}
