@echo off
REM Generated by register_report_audit_task.ps1 -- do not edit by hand.
REM Publishes reports/AUDIT_STATUS.md to origin/main; see
REM scripts/scheduled_report_audit.py for what it does and why.
set PYTHONPATH=D:\ccc\pro-web-60d-strategy
set GIT_TERMINAL_PROMPT=0
cd /d "D:\ccc\pro-web-60d-strategy"
"C:\Users\30834\miniconda3\python.exe" "D:\ccc\pro-web-60d-strategy\scripts\scheduled_report_audit.py" --quiet >> "D:\ccc\pro-web-60d-strategy\logs\report_audit\scheduler.out" 2>&1
