@echo off
REM Generated by register_fixup_task.ps1 -- do not edit by hand.
REM Reads the newest expert/ML report (written by the GPT-Pro web review) and
REM fixes the code it names; see scripts/run_fixup.py.
set PYTHONPATH=D:\ccc\pro-web-60d-strategy
set GIT_TERMINAL_PROMPT=0
cd /d "D:\ccc\pro-web-60d-strategy"
"C:\Users\30834\miniconda3\python.exe" "D:\ccc\pro-web-60d-strategy\scripts\run_fixup.py" >> "D:\ccc\pro-web-60d-strategy\logs\fixup\scheduler.out" 2>&1
